import type { EMRRecord } from './EMRPrintTemplate';

export interface HospitalInfo {
  name: string;
  address: string;
  phone: string;
  email: string;
  website: string;
  generatedBy: string;
  logoText: string;
}

interface IPDPrintTemplateProps {
  hospital: HospitalInfo;
  record: EMRRecord;
}

export const IPDPrintTemplate = ({ hospital, record }: IPDPrintTemplateProps) => {
  const generatedOn = record.generatedOn || new Date().toLocaleString();

  return (
    <div className="print:p-0 p-6 text-slate-900 bg-white">
      <style>{`
        @media print {
          .print-hide { display: none !important; }
          .page-break { page-break-after: always; break-after: page; }
          .avoid-break { page-break-inside: avoid; break-inside: avoid; }
        }
      `}</style>

      {/* Page 1 */}
      <section className="avoid-break">
        <div className="flex items-start justify-between gap-4 border-b border-slate-300 pb-4 mb-4">
          <div>
            <div className="flex items-center gap-3">
              <div className="w-16 h-16 rounded-lg border border-slate-400 flex items-center justify-center text-lg font-bold uppercase tracking-[0.2em]">
                {hospital.logoText}
              </div>
              <div>
                <p className="text-base font-semibold uppercase tracking-[0.06em]">{hospital.name}</p>
                <p className="text-xs text-slate-600 mt-1">{hospital.address}</p>
                <p className="text-xs text-slate-600">Phone: {hospital.phone}</p>
                <p className="text-xs text-slate-600">Email: {hospital.email}</p>
                <p className="text-xs text-slate-600">Website: {hospital.website}</p>
              </div>
            </div>
          </div>
          <div className="text-right text-xs text-slate-600 space-y-2">
            <div className="border border-slate-300 p-2 inline-block uppercase tracking-[0.12em]">Barcode</div>
            <div className="border border-slate-300 p-2 inline-block uppercase tracking-[0.12em]">QR CODE</div>
            <p>Generated: {generatedOn}</p>
            <p>Generated By: {hospital.generatedBy}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1.7fr_1fr] gap-6 mb-6 avoid-break">
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Patient Details</p>
            <div className="grid grid-cols-2 gap-4 text-xs text-slate-700">
              <div>
                <p className="font-semibold">UHID</p>
                <p>{record.uhid || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Patient Name</p>
                <p>{record.patientName || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Age</p>
                <p>{record.age != null ? `${record.age} yrs` : '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Gender</p>
                <p>{record.gender || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Blood Group</p>
                <p>{record.bloodGroup || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Department</p>
                <p>{record.department || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Contact</p>
                <p>{record.mobile || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Admission Date</p>
                <p>{record.admissionDate || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Admission Time</p>
                <p>{record.admissionTime || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Ward / Bed</p>
                <p>{record.ward || '—'} / {record.bed || '—'}</p>
              </div>
            </div>
          </div>
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Admission Details</p>
            <div className="text-xs text-slate-700 space-y-3">
              <div><span className="font-semibold">Admission Diagnosis:</span> {record.admissionDiagnosis || '—'}</div>
              <div><span className="font-semibold">Consultant:</span> {record.consultant || '—'}</div>
              <div><span className="font-semibold">Attending Doctor:</span> {record.doctor || '—'}</div>
              <div><span className="font-semibold">Specialty:</span> {record.specialty || '—'}</div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 mb-6 avoid-break">
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Chief Complaint</p>
            <p className="text-sm text-slate-700 whitespace-pre-line">{record.chiefComplaint || '—'}</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="border border-slate-300 rounded-xl p-4">
              <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">History of Present Illness</p>
              <p className="text-sm text-slate-700 whitespace-pre-line">{record.historyOfPresentIllness || '—'}</p>
            </div>
            <div className="border border-slate-300 rounded-xl p-4">
              <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Past History / Allergies</p>
              <p className="text-sm text-slate-700 whitespace-pre-line">{(record.pastMedicalHistory && record.pastMedicalHistory.length > 0) ? record.pastMedicalHistory.join('; ') : '—'}</p>
              <p className="text-sm text-slate-700 mt-3"><span className="font-semibold">Allergies:</span> {record.allergyHistory || '—'}</p>
            </div>
          </div>
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Family / Personal History</p>
            <p className="text-sm text-slate-700 whitespace-pre-line">Family: {record.familyHistory || '—'}</p>
            <p className="text-sm text-slate-700 mt-2">Personal: {record.personalHistory || '—'}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6 avoid-break">
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Initial Vitals</p>
            <table className="w-full text-xs text-slate-700 border-collapse">
              <tbody>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Height</td><td className="py-2 border-b border-slate-200">{record.height || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Weight</td><td className="py-2 border-b border-slate-200">{record.weight || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">BMI</td><td className="py-2 border-b border-slate-200">{record.bmi || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Temp</td><td className="py-2 border-b border-slate-200">{record.temperature || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Pulse</td><td className="py-2 border-b border-slate-200">{record.pulse || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Respiration</td><td className="py-2 border-b border-slate-200">{record.respiration || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">BP</td><td className="py-2 border-b border-slate-200">{record.bloodPressure || '—'}</td></tr>
                <tr><td className="py-2 font-semibold">SpO₂</td><td className="py-2">{record.spo2 || '—'}</td></tr>
              </tbody>
            </table>
          </div>
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Initial Clinical Examination</p>
            <p className="text-sm text-slate-700 whitespace-pre-line">{record.generalExamination || '—'}</p>
          </div>
        </div>
      </section>

      <div className="page-break"></div>

      {/* Page 2 */}
      <section className="avoid-break">
        <div className="flex items-center justify-between mb-4">
          <div>
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500">Inpatient Progress</p>
            <p className="text-sm font-semibold">Clinical Notes, Medications, Orders</p>
          </div>
          <p className="text-xs text-slate-500">Page 2 of 3</p>
        </div>

        <div className="grid grid-cols-1 gap-4 mb-6">
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Clinical Notes</p>
            <p className="text-sm text-slate-700 whitespace-pre-line">{record.clinicalNotes || '—'}</p>
          </div>
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Diagnosis</p>
            <p className="text-sm text-slate-700 whitespace-pre-line">{record.diagnosis || '—'}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 mb-6">
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Medication Record</p>
            {(record.prescriptions && record.prescriptions.length > 0) ? (
              <table className="w-full text-xs text-slate-700 border-collapse">
                <thead>
                  <tr className="bg-slate-100">
                    <th className="py-2 px-3 text-left font-semibold">Medicine</th>
                    <th className="py-2 px-3 text-left font-semibold">Dose</th>
                    <th className="py-2 px-3 text-left font-semibold">Frequency</th>
                    <th className="py-2 px-3 text-left font-semibold">Duration</th>
                    <th className="py-2 px-3 text-left font-semibold">Instructions</th>
                  </tr>
                </thead>
                <tbody>
                  {record.prescriptions.map((item, index) => (
                    <tr key={index} className="border-t border-slate-200">
                      <td className="py-2 px-3">{item.medicine}</td>
                      <td className="py-2 px-3">{item.dosage}</td>
                      <td className="py-2 px-3">{item.frequency}</td>
                      <td className="py-2 px-3">{item.duration}</td>
                      <td className="py-2 px-3">{item.instructions || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : <p className="text-sm text-slate-500">No medications recorded.</p>}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Laboratory Orders</p>
            {(record.investigations && record.investigations.length > 0) ? (
              <table className="w-full text-xs text-slate-700 border-collapse">
                <thead>
                  <tr className="bg-slate-100">
                    <th className="py-2 px-3 text-left font-semibold">Test</th>
                    <th className="py-2 px-3 text-left font-semibold">Result</th>
                    <th className="py-2 px-3 text-left font-semibold">Normal</th>
                  </tr>
                </thead>
                <tbody>
                  {record.investigations.map((item, index) => (
                    <tr key={index} className="border-t border-slate-200">
                      <td className="py-2 px-3">{item.test}</td>
                      <td className="py-2 px-3">{item.result}</td>
                      <td className="py-2 px-3">{item.normalRange || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : <p className="text-sm text-slate-500">No lab results available.</p>}
          </div>
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Vitals</p>
            <table className="w-full text-xs text-slate-700 border-collapse">
              <tbody>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">BP</td><td className="py-2 border-b border-slate-200">{record.vitals?.bp || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Pulse</td><td className="py-2 border-b border-slate-200">{record.vitals?.pulse || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Temp</td><td className="py-2 border-b border-slate-200">{record.vitals?.temp || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">SpO₂</td><td className="py-2 border-b border-slate-200">{record.vitals?.spo2 || '—'}</td></tr>
                <tr><td className="py-2 border-b border-slate-200 font-semibold">Weight</td><td className="py-2 border-b border-slate-200">{record.vitals?.weight || '—'}</td></tr>
                <tr><td className="py-2 font-semibold">Height</td><td className="py-2">{record.vitals?.height || '—'}</td></tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <div className="page-break"></div>

      {/* Page 3 */}
      <section className="avoid-break">
        <div className="flex items-center justify-between mb-4">
          <div>
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500">Inpatient Summary</p>
            <p className="text-sm font-semibold">Discharge, Follow-up & Signatures</p>
          </div>
          <p className="text-xs text-slate-500">Page 3 of 3</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Admission Summary</p>
            <div className="text-sm text-slate-700 space-y-2">
              <p><span className="font-semibold">Admission Date:</span> {record.admissionDate || '—'}</p>
              <p><span className="font-semibold">Discharge Status:</span> {record.dischargeStatus || '—'}</p>
              <p><span className="font-semibold">Billing Status:</span> {record.billingStatus || '—'}</p>
              <p><span className="font-semibold">Consultant:</span> {record.consultant || record.doctor || '—'}</p>
            </div>
          </div>
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Follow-up</p>
            <div className="text-sm text-slate-700 space-y-2">
              <p><span className="font-semibold">Next Follow-up:</span> {record.followUpDate || '—'}</p>
              <p><span className="font-semibold">Ward / Bed:</span> {record.ward || '—'} / {record.bed || '—'}</p>
              <p><span className="font-semibold">Referral Source:</span> {record.referralSource || '—'}</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 mb-6">
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Hospital Course</p>
            <p className="text-sm text-slate-700 whitespace-pre-line">{record.hospitalCourse || '—'}</p>
          </div>
          <div className="border border-slate-300 rounded-xl p-4 avoid-break">
            <p className="text-[11px] uppercase tracking-[0.26em] text-slate-500 mb-3">Discharge Advice</p>
            <p className="text-sm text-slate-700 whitespace-pre-line">{record.dischargeAdvice || '—'}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-end text-xs text-slate-600">
          <div className="space-y-3 border-t border-slate-400 pt-3">
            <p className="font-semibold">Doctor Signature</p>
          </div>
          <div className="space-y-3 border-t border-slate-400 pt-3">
            <p className="font-semibold">Nurse / Ward In-charge</p>
          </div>
          <div className="text-right space-y-2">
            <div className="border border-slate-300 p-2">Hospital Seal</div>
            <p>Generated: {generatedOn}</p>
            <p>Generated By: {hospital.generatedBy}</p>
            <p className="font-semibold">Page 3 of 3</p>
          </div>
        </div>
      </section>
    </div>
  );
};
