import type { EMRRecord } from './EMRPrintTemplate';

export interface HospitalInfo {
  name: string;
  address: string;
  phone: string;
  email: string;
  website: string;
  generatedBy: string;
  logoText: string;
}

interface OPDPrintTemplateProps {
  hospital: HospitalInfo;
  record: EMRRecord;
}

export const OPDPrintTemplate = ({ hospital, record }: OPDPrintTemplateProps) => {
  const generatedOn = record.generatedOn || new Date().toLocaleString();

  return (
    <div className="print:p-0 p-6 text-slate-900 bg-white">
      <style>{`
        @media print {
          .print-hide { display: none !important; }
          .page-break { page-break-after: always; break-after: page; }
          .avoid-break { page-break-inside: avoid; break-inside: avoid; }
          .print-header, .print-footer { width: 100%; }
        }
      `}</style>

      {/* Page 1 */}
      <section className="print-header border-b border-slate-300 pb-4 mb-4 avoid-break">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-3">
              <div className="w-16 h-16 rounded-lg border border-slate-400 flex items-center justify-center text-lg font-bold tracking-[0.2em] uppercase">
                {hospital.logoText}
              </div>
              <div>
                <p className="text-base font-semibold tracking-[0.08em] uppercase">{hospital.name}</p>
                <p className="text-xs text-slate-600 mt-1">{hospital.address}</p>
                <p className="text-xs text-slate-600">Phone: {hospital.phone}</p>
                <p className="text-xs text-slate-600">Email: {hospital.email}</p>
                <p className="text-xs text-slate-600">Website: {hospital.website}</p>
              </div>
            </div>
          </div>
          <div className="text-right text-xs text-slate-600 space-y-2">
            <div className="border border-slate-300 p-2 inline-block text-[10px] uppercase tracking-[0.15em]">QR CODE</div>
            <div className="border border-slate-300 p-2 mt-2 text-[10px] font-mono">|| ||| |||| ||| |</div>
            <p>Generated: {generatedOn}</p>
            <p>Generated By: {hospital.generatedBy}</p>
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-6 mb-6 avoid-break">
        <div className="grid grid-cols-1 lg:grid-cols-[1.7fr_1fr] gap-6">
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Patient Information</p>
            <div className="grid grid-cols-2 gap-x-4 gap-y-3 text-xs text-slate-700">
              <div>
                <p className="font-semibold">UHID</p>
                <p>{record.uhid || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Patient Name</p>
                <p>{record.patientName || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Age</p>
                <p>{record.age != null ? `${record.age} yrs` : '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Gender</p>
                <p>{record.gender || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">DOB</p>
                <p>{record.dob || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Blood Group</p>
                <p>{record.bloodGroup || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Nationality</p>
                <p>{record.nationality || '—'}</p>
              </div>
              <div>
                <p className="font-semibold">Occupation</p>
                <p>{record.occupation || '—'}</p>
              </div>
              <div className="lg:col-span-2">
                <p className="font-semibold">Contact</p>
                <p>{record.mobile || '—'} / {record.email || '—'}</p>
              </div>
              <div className="lg:col-span-2">
                <p className="font-semibold">Address</p>
                <p>{record.address || '—'}</p>
              </div>
            </div>
          </div>

          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Patient Photo</p>
            <div className="h-52 border border-slate-300 rounded-xl bg-slate-50 flex items-center justify-center text-slate-400 uppercase tracking-[0.2em] text-[11px]">
              Photo
            </div>
          </div>
        </div>
      </section>

      <section className="border border-slate-300 rounded-xl p-4 mb-6 avoid-break">
        <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Visit Information</p>
        <div className="grid grid-cols-2 gap-4 text-xs text-slate-700">
          <div>
            <p className="font-semibold">OP Number</p>
            <p>{record.visitId || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Visit Date</p>
            <p>{record.visitDate || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Visit Time</p>
            <p>{record.visitTime || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Department</p>
            <p>{record.department || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Doctor</p>
            <p>{record.doctor || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Consultation Type</p>
            <p>{record.consultationType || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Token Number</p>
            <p>{record.tokenNumber || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Visit Status</p>
            <p>{record.visitStatus || '—'}</p>
          </div>
          <div className="lg:col-span-2">
            <p className="font-semibold">Referral Source</p>
            <p>{record.referralSource || '—'}</p>
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-4 mb-6 avoid-break">
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Chief Complaint</p>
          <p className="text-sm leading-6 text-slate-700 whitespace-pre-line">{record.chiefComplaint || '—'}</p>
        </div>
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">History of Present Illness</p>
          <p className="text-sm leading-6 text-slate-700 whitespace-pre-line">{record.historyOfPresentIllness || '—'}</p>
        </div>
      </section>

      <section className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6 avoid-break">
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Past Medical History</p>
          <ul className="list-disc list-inside text-sm text-slate-700 space-y-1">
            {(record.pastMedicalHistory && record.pastMedicalHistory.length > 0)
              ? record.pastMedicalHistory.map((item, index) => <li key={index}>{item}</li>)
              : <li>None reported</li>
            }
          </ul>
        </div>
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Surgical History</p>
          <ul className="list-disc list-inside text-sm text-slate-700 space-y-1">
            {(record.surgicalHistory && record.surgicalHistory.length > 0)
              ? record.surgicalHistory.map((item, index) => <li key={index}>{item}</li>)
              : <li>None reported</li>
            }
          </ul>
        </div>
      </section>

      <section className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6 avoid-break">
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Family History</p>
          <p className="text-sm leading-6 text-slate-700 whitespace-pre-line">{record.familyHistory || '—'}</p>
        </div>
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Allergy History</p>
          <p className="text-sm leading-6 text-slate-700 whitespace-pre-line">{record.allergyHistory || '—'}</p>
        </div>
      </section>

      <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-6 avoid-break">
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Social History</p>
          <div className="grid grid-cols-1 gap-3 text-sm text-slate-700">
            <div><span className="font-semibold">Smoking:</span> {record.socialHistory?.smoking || '—'}</div>
            <div><span className="font-semibold">Alcohol:</span> {record.socialHistory?.alcohol || '—'}</div>
            <div><span className="font-semibold">Occupation:</span> {record.socialHistory?.occupation || '—'}</div>
            <div><span className="font-semibold">Food Habit:</span> {record.socialHistory?.foodHabit || '—'}</div>
          </div>
        </div>
        <div className="border border-slate-300 rounded-xl p-4">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Vitals</p>
          <table className="w-full text-xs text-slate-700 border-collapse">
            <tbody>
              <tr><td className="py-2 border-b border-slate-200 font-semibold">Height</td><td className="py-2 border-b border-slate-200">{record.height || '—'}</td></tr>
              <tr><td className="py-2 border-b border-slate-200 font-semibold">Weight</td><td className="py-2 border-b border-slate-200">{record.weight || '—'}</td></tr>
              <tr><td className="py-2 border-b border-slate-200 font-semibold">BMI</td><td className="py-2 border-b border-slate-200">{record.bmi || '—'}</td></tr>
              <tr><td className="py-2 border-b border-slate-200 font-semibold">Temp</td><td className="py-2 border-b border-slate-200">{record.temperature || '—'}</td></tr>
              <tr><td className="py-2 border-b border-slate-200 font-semibold">Pulse</td><td className="py-2 border-b border-slate-200">{record.pulse || '—'}</td></tr>
              <tr><td className="py-2 border-b border-slate-200 font-semibold">Respiration</td><td className="py-2 border-b border-slate-200">{record.respiration || '—'}</td></tr>
              <tr><td className="py-2 border-b border-slate-200 font-semibold">Blood Pressure</td><td className="py-2 border-b border-slate-200">{record.bloodPressure || '—'}</td></tr>
              <tr><td className="py-2 font-semibold">SpO₂</td><td className="py-2">{record.spo2 || '—'}</td></tr>
              <tr><td className="py-2 font-semibold">Pain Scale</td><td className="py-2">{record.painScale || '—'}</td></tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="border border-slate-300 rounded-xl p-4 mb-6 avoid-break">
        <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Physical Examination</p>
        <div className="grid grid-cols-1 gap-4 text-sm text-slate-700">
          <div>
            <p className="font-semibold">General Examination</p>
            <p className="whitespace-pre-line">{record.generalExamination || '—'}</p>
          </div>
          <div>
            <p className="font-semibold">Systemic Examination</p>
            <p className="whitespace-pre-line">{record.systemicExamination || '—'}</p>
          </div>
        </div>
      </section>

      <div className="page-break"></div>

      {/* Page 2 */}
      <section className="avoid-break">
        <div className="flex items-center justify-between mb-4">
          <div>
            <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Outpatient EMR</p>
            <p className="text-sm font-semibold">Diagnosis & Prescription</p>
          </div>
          <p className="text-xs text-slate-500">Page 2 of 2</p>
        </div>

        <div className="border border-slate-300 rounded-xl p-4 mb-6">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Diagnosis</p>
          <table className="w-full text-xs text-slate-700 border-collapse">
            <thead>
              <tr className="bg-slate-100">
                <th className="py-2 px-3 text-left font-semibold">ICD-10 Code</th>
                <th className="py-2 px-3 text-left font-semibold">Description</th>
              </tr>
            </thead>
            <tbody>
              {(record.icdCodes && record.icdCodes.length > 0) ? record.icdCodes.map((item, index) => (
                <tr key={index} className="border-t border-slate-200">
                  <td className="py-2 px-3">{item.code}</td>
                  <td className="py-2 px-3">{item.description}</td>
                </tr>
              )) : (
                <tr><td colSpan={2} className="py-4 px-3 text-slate-500">No diagnosis codes available.</td></tr>
              )}
            </tbody>
          </table>
        </div>

        <div className="border border-slate-300 rounded-xl p-4 mb-6">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Prescription</p>
          <table className="w-full text-xs text-slate-700 border-collapse">
            <thead>
              <tr className="bg-slate-100">
                <th className="py-2 px-3 text-left font-semibold">Medicine</th>
                <th className="py-2 px-3 text-left font-semibold">Strength</th>
                <th className="py-2 px-3 text-left font-semibold">Dose</th>
                <th className="py-2 px-3 text-left font-semibold">Route</th>
                <th className="py-2 px-3 text-left font-semibold">Frequency</th>
                <th className="py-2 px-3 text-left font-semibold">Duration</th>
                <th className="py-2 px-3 text-left font-semibold">Instructions</th>
              </tr>
            </thead>
            <tbody>
              {(record.prescriptions && record.prescriptions.length > 0) ? record.prescriptions.map((item, index) => (
                <tr key={index} className="border-t border-slate-200">
                  <td className="py-2 px-3">{item.medicine}</td>
                  <td className="py-2 px-3">{item.dosage}</td>
                  <td className="py-2 px-3">{item.dosage}</td>
                  <td className="py-2 px-3">Oral</td>
                  <td className="py-2 px-3">{item.frequency}</td>
                  <td className="py-2 px-3">{item.duration}</td>
                  <td className="py-2 px-3">{item.instructions || '—'}</td>
                </tr>
              )) : (
                <tr><td colSpan={7} className="py-4 px-3 text-slate-500">No prescription items available.</td></tr>
              )}
            </tbody>
          </table>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-6">
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Laboratory Orders</p>
            <table className="w-full text-xs text-slate-700 border-collapse">
              <thead>
                <tr className="bg-slate-100">
                  <th className="py-2 px-3 text-left font-semibold">Test</th>
                  <th className="py-2 px-3 text-left font-semibold">Status</th>
                  <th className="py-2 px-3 text-left font-semibold">Priority</th>
                </tr>
              </thead>
              <tbody>
                {(record.labOrders && record.labOrders.length > 0) ? record.labOrders.map((item, index) => (
                  <tr key={index} className="border-t border-slate-200">
                    <td className="py-2 px-3">{item.test}</td>
                    <td className="py-2 px-3">{item.status}</td>
                    <td className="py-2 px-3">{item.priority}</td>
                  </tr>
                )) : (
                  <tr><td colSpan={3} className="py-4 px-3 text-slate-500">None ordered.</td></tr>
                )}
              </tbody>
            </table>
          </div>
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Radiology Orders</p>
            <table className="w-full text-xs text-slate-700 border-collapse">
              <thead>
                <tr className="bg-slate-100">
                  <th className="py-2 px-3 text-left font-semibold">Study</th>
                  <th className="py-2 px-3 text-left font-semibold">Status</th>
                </tr>
              </thead>
              <tbody>
                {(record.radiologyOrders && record.radiologyOrders.length > 0) ? record.radiologyOrders.map((item, index) => (
                  <tr key={index} className="border-t border-slate-200">
                    <td className="py-2 px-3">{item.study}</td>
                    <td className="py-2 px-3">{item.status}</td>
                  </tr>
                )) : (
                  <tr><td colSpan={2} className="py-4 px-3 text-slate-500">None ordered.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 mb-6 avoid-break">
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Clinical Notes</p>
            <p className="text-sm leading-6 text-slate-700 whitespace-pre-line">{record.clinicalNotes || '—'}</p>
          </div>
          <div className="border border-slate-300 rounded-xl p-4">
            <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Doctor Advice</p>
            <p className="text-sm leading-6 text-slate-700 whitespace-pre-line">{record.doctorAdvice || '—'}</p>
          </div>
        </div>

        <div className="border border-slate-300 rounded-xl p-4 mb-6 avoid-break">
          <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500 mb-3">Follow-up</p>
          <div className="grid grid-cols-2 gap-4 text-xs text-slate-700">
            <div>
              <p className="font-semibold">Date</p>
              <p>{record.followUp?.date || '—'}</p>
            </div>
            <div>
              <p className="font-semibold">Doctor</p>
              <p>{record.followUp?.doctor || '—'}</p>
            </div>
            <div>
              <p className="font-semibold">Department</p>
              <p>{record.followUp?.department || '—'}</p>
            </div>
            <div>
              <p className="font-semibold">Reason</p>
              <p>{record.followUp?.reason || '—'}</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4 items-end text-xs text-slate-600">
          <div className="space-y-3">
            <div className="border-t border-slate-400 pt-3">
              <p className="font-semibold">Doctor Signature</p>
            </div>
            <div className="border border-slate-300 p-2 text-center">Hospital Seal</div>
          </div>
          <div className="text-right">
            <p>Generated Date: {generatedOn}</p>
            <p>Generated By: {hospital.generatedBy}</p>
            <p className="mt-4 font-semibold">Page 2 of 2</p>
          </div>
        </div>
      </section>
    </div>
  );
};
