version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    container_name: carefusions_frontend
    ports:
      - "5176:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./Python
    container_name: carefusions_backend
    ports:
      - "8005:8000"
    volumes:
      - ./Python:/app
    environment:
      - PYTHONUNBUFFERED=1
