import { useState, useEffect } from 'react';
import {
  Plus, Search, Filter, Download, Edit2, Trash2, AlertTriangle,
  Save, RefreshCw, Mail
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '../../../components/ui/Button';
import { Modal } from '../../../components/ui/Modal';
import { exportToExcel } from '../../../utils/exportToExcel';

const API_BASE = import.meta.env.VITE_API_URL as string;

interface EmailTemplateRecord {
  id: number;
  templateCode: string;
  templateName: string;
  module: string;
  event: string;
  emailSubject: string;
  emailBody: string;
  attachmentAllowed: boolean;
  attachmentType: string;
  status: string;
  remarks: string;
  createdBy?: string;
  createdDate?: string;
  updatedBy?: string;
  updatedDate?: string;
}

// TemplateCode is auto-generated by the backend (EML-001 format)
type EmailTemplateForm = Omit<EmailTemplateRecord, 'id' | 'templateCode' | 'createdBy' | 'createdDate' | 'updatedBy' | 'updatedDate'>;

const emptyData: EmailTemplateForm = {
  templateName: '',
  module: '',
  event: '',
  emailSubject: '',
  emailBody: '',
  attachmentAllowed: false,
  attachmentType: '',
  status: 'Active',
  remarks: ''
};

const LIMITS = {
  templateName: 150, module: 100, event: 100,
  emailSubject: 300, emailBody: 10000, attachmentType: 100, remarks: 500,
};

const MODULES = ['Patient Registration', 'Appointment', 'Billing', 'Laboratory', 'Discharge'];
const EVENTS = ['Appointment Booked', 'Appointment Reminder', 'Bill Generated', 'Discharge Completed'];
const ATTACHMENT_TYPES = ['PDF Invoice', 'Medical Report', 'Prescription'];
const VARIABLES = ['{{PatientName}}', '{{DoctorName}}', '{{InvoiceNo}}', '{{AppointmentDate}}', '{{HospitalName}}'];

const mapApiToRecord = (item: Record<string, unknown>): EmailTemplateRecord => ({
  id:                item.id                as number,
  templateCode:      item.templateCode      as string,
  templateName:      item.templateName      as string,
  module:            item.module            as string,
  event:             item.event             as string,
  emailSubject:      item.emailSubject      as string,
  emailBody:         item.emailBody         as string,
  attachmentAllowed: Boolean(item.attachmentAllowed),
  attachmentType:    (item.attachmentType    as string) ?? '',
  status:            item.status            as string,
  remarks:           (item.remarks           as string) ?? '',
  createdBy:         (item.createdBy         as string) ?? undefined,
  createdDate:       item.createdDate ? String(item.createdDate).split('T')[0] : undefined,
  updatedBy:         (item.updatedBy         as string) ?? undefined,
  updatedDate:       item.updatedDate ? String(item.updatedDate).split('T')[0] : undefined,
});

export const EmailMaster = () => {
  const [records, setRecords] = useState<EmailTemplateRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [nextCode, setNextCode] = useState('');

  // Filter States
  const [showFilters, setShowFilters] = useState(false);
  const [filterModule, setFilterModule] = useState('');
  const [filterEvent, setFilterEvent] = useState('');
  const [filterStatus, setFilterStatus] = useState('');

  // Form States
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState<EmailTemplateRecord | null>(null);
  const [formData, setFormData] = useState<EmailTemplateForm>(emptyData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // ── Fetch templates ──────────────────────────────────────────
  const fetchTemplates = async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/email-templates/`);
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data: Record<string, unknown>[] = await res.json();
      setRecords(data.map(mapApiToRecord));
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Failed to load email templates');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchTemplates(); }, []);

  const fetchNextCode = async () => {
    setNextCode('');
    try {
      const res = await fetch(`${API_BASE}/email-templates/next-code`);
      if (res.ok) setNextCode((await res.json()).templateCode ?? '');
    } catch { setNextCode(''); }
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.templateName.trim()) newErrors.templateName = 'Template Name is required';
    if (!formData.module.trim()) newErrors.module = 'Module is required';
    if (!formData.event.trim()) newErrors.event = 'Trigger Event is required';
    if (!formData.emailSubject.trim()) newErrors.emailSubject = 'Email Subject is required';
    if (!formData.emailBody.trim()) newErrors.emailBody = 'Email Body is required';
    else if (formData.emailBody.length > LIMITS.emailBody) newErrors.emailBody = `Max ${LIMITS.emailBody} characters`;

    // Business rule: attachment type required when attachments are allowed
    if (formData.attachmentAllowed && !formData.attachmentType.trim())
      newErrors.attachmentType = 'Select an attachment type';

    // Client-side hint (server is the source of truth)
    if (records.some(r => r.templateName.toLowerCase() === formData.templateName.trim().toLowerCase() && r.id !== selectedRecord?.id))
      newErrors.templateName = 'Template Name must be unique';

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleCreateNew = () => {
    setSelectedRecord(null);
    setFormData(emptyData);
    setErrors({});
    setIsFormOpen(true);
    fetchNextCode();
  };

  const handleEdit = (record: EmailTemplateRecord) => {
    setSelectedRecord(record);
    const { id, templateCode, createdBy, createdDate, updatedBy, updatedDate, ...rest } = record;
    setFormData(rest);
    setErrors({});
    setIsFormOpen(true);
  };

  const handleDeleteRequest = (record: EmailTemplateRecord) => {
    setSelectedRecord(record);
    setIsDeleteOpen(true);
  };

  const insertVariable = (variable: string) => {
    setFormData(prev => {
      const next = prev.emailBody + variable;
      return { ...prev, emailBody: next.slice(0, LIMITS.emailBody) };
    });
  };

  const handleSaveForm = async () => {
    if (!validateForm()) return;
    setIsSaving(true);
    setApiError(null);
    try {
      const body = {
        templateName:      formData.templateName.trim(),
        module:            formData.module,
        event:             formData.event,
        emailSubject:      formData.emailSubject.trim(),
        emailBody:         formData.emailBody,
        attachmentAllowed: formData.attachmentAllowed,
        attachmentType:    formData.attachmentAllowed ? (formData.attachmentType || null) : null,
        status:            formData.status,
        remarks:           formData.remarks || null,
      };

      let res: Response;
      if (selectedRecord) {
        res = await fetch(`${API_BASE}/email-templates/${selectedRecord.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, updatedBy: 'Admin' }),
        });
      } else {
        res = await fetch(`${API_BASE}/email-templates/`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, createdBy: 'Admin' }),
        });
      }
      if (!res.ok) {
        const data = await res.json().catch(() => null);
        let detail = `Save failed: ${res.status}`;
        if (data && typeof data.detail === 'string') detail = data.detail;
        else if (data && Array.isArray(data.detail) && data.detail[0]?.msg) detail = data.detail[0].msg;
        throw new Error(detail);
      }

      await fetchTemplates();
      setIsFormOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setIsSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!selectedRecord) return;
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/email-templates/${selectedRecord.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`Delete failed: ${res.status}`);
      await fetchTemplates();
      setIsDeleteOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Delete failed');
      setIsDeleteOpen(false);
    }
  };

  const filteredRecords = records.filter(record => {
    const matchesSearch =
      record.templateName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.templateCode.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesModule = !filterModule || record.module === filterModule;
    const matchesEvent = !filterEvent || record.event === filterEvent;
    const matchesStatus = !filterStatus || record.status === filterStatus;
    return matchesSearch && matchesModule && matchesEvent && matchesStatus;
  });

  const uniqueModules = Array.from(new Set([...MODULES, ...records.map(r => r.module)].filter(Boolean)));
  const uniqueEvents = Array.from(new Set([...EVENTS, ...records.map(r => r.event)].filter(Boolean)));

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="h-full flex flex-col relative"
    >
      {apiError && (
        <div className="mb-4 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span className="flex-1">{apiError}</span>
          <button onClick={() => setApiError(null)} className="text-red-500 hover:text-red-700 font-medium">Dismiss</button>
        </div>
      )}

      {!isFormOpen ? (
        <>
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-slate-800">Email Template Master</h1>
            </div>
            <div className="flex gap-3">
              <Button variant="outline" icon={RefreshCw} onClick={fetchTemplates}>Refresh</Button>
              <Button variant="outline" icon={Download} onClick={() => exportToExcel(records, 'EmailMaster')}>Export</Button>
              <Button variant="filled" color="primary" icon={Plus} onClick={handleCreateNew}>
                Add Template
              </Button>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex flex-wrap gap-4 items-center justify-between">
              <div className="relative flex-1 max-w-md">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search by Code or Name..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary text-sm"
                />
              </div>
              <Button
                variant={showFilters ? "filled" : "outline"}
                color="secondary"
                icon={Filter}
                onClick={() => setShowFilters(!showFilters)}
              >
                Filters
              </Button>
            </div>

            <AnimatePresence>
              {showFilters && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="border-b border-slate-200 bg-slate-50/50 p-4"
                >
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <select
                      value={filterModule}
                      onChange={(e) => setFilterModule(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Modules</option>
                      {uniqueModules.map(m => <option key={m} value={m}>{m}</option>)}
                    </select>
                    <select
                      value={filterEvent}
                      onChange={(e) => setFilterEvent(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Events</option>
                      {uniqueEvents.map(e => <option key={e} value={e}>{e}</option>)}
                    </select>
                    <select
                      value={filterStatus}
                      onChange={(e) => setFilterStatus(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Statuses</option>
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="flex-1 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600">
                  <tr>
                    <th className="px-4 py-3 font-medium">Template Code</th>
                    <th className="px-4 py-3 font-medium">Template Name</th>
                    <th className="px-4 py-3 font-medium">Module</th>
                    <th className="px-4 py-3 font-medium">Trigger Event</th>
                    <th className="px-4 py-3 font-medium text-center">Status</th>
                    <th className="px-4 py-3 font-medium text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {isLoading ? (
                    <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">Loading templates…</td></tr>
                  ) : filteredRecords.length > 0 ? (
                    filteredRecords.map((record) => (
                      <tr key={record.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-3 font-medium text-slate-800">{record.templateCode}</td>
                        <td className="px-4 py-3 font-medium text-primary">{record.templateName}</td>
                        <td className="px-4 py-3 text-slate-600">{record.module}</td>
                        <td className="px-4 py-3 text-slate-600">
                          <span className="inline-flex px-2 py-1 bg-slate-100 text-slate-600 rounded-md text-xs font-medium">
                            {record.event}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${
                            record.status === 'Active'
                              ? 'bg-emerald-50 text-emerald-600 border border-emerald-200'
                              : 'bg-red-50 text-red-600 border border-red-200'
                          }`}>
                            {record.status}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => handleEdit(record)}
                              className="p-1.5 text-slate-400 hover:text-primary hover:bg-primary/5 rounded-lg transition-colors"
                              title="Edit"
                            >
                              <Edit2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteRequest(record)}
                              className="p-1.5 text-red-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={6} className="px-4 py-8 text-center text-slate-500">
                        No templates found matching your criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </>
      ) : (
        <>
          <div className="flex justify-between items-center mb-6">
            <div>
              <h1 className="text-2xl font-bold text-slate-800">
                {selectedRecord ? `Edit Template: ${selectedRecord.templateName}` : 'Add Email Template'}
              </h1>
              <p className="text-slate-500 text-sm">Configure automated Email messaging rules</p>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="flex-1 overflow-y-auto p-6 space-y-8">

              {/* Basic Information */}
              <section>
                <h3 className="text-lg font-bold text-slate-800 mb-4 border-b border-slate-100 pb-2">Basic Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Template Code</label>
                    <input type="text" value={selectedRecord ? selectedRecord.templateCode : (nextCode || 'Auto-generated')} readOnly className="w-full px-4 py-2 bg-slate-100 border border-slate-200 rounded-xl text-sm text-slate-500 cursor-not-allowed focus:outline-none" />
                  </div>
                  <div className="lg:col-span-3">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Template Name <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.templateName} value={formData.templateName} onChange={e => setFormData({...formData, templateName: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.templateName ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.templateName && <p className="text-red-500 text-xs mt-1">{errors.templateName}</p>}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Module <span className="text-red-500">*</span></label>
                    <select value={formData.module} onChange={e => setFormData({...formData, module: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.module ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`}>
                      <option value="">Select Module</option>
                      {MODULES.map(m => <option key={m} value={m}>{m}</option>)}
                    </select>
                    {errors.module && <p className="text-red-500 text-xs mt-1">{errors.module}</p>}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Trigger Event <span className="text-red-500">*</span></label>
                    <select value={formData.event} onChange={e => setFormData({...formData, event: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.event ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`}>
                      <option value="">Select Event</option>
                      {EVENTS.map(ev => <option key={ev} value={ev}>{ev}</option>)}
                    </select>
                    {errors.event && <p className="text-red-500 text-xs mt-1">{errors.event}</p>}
                  </div>
                </div>
              </section>

              {/* Email Configuration */}
              <section>
                <div className="flex items-center gap-2 mb-4 border-b border-slate-100 pb-2">
                  <Mail className="w-5 h-5 text-primary" />
                  <h3 className="text-lg font-bold text-slate-800">Email Configuration</h3>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                  <div className="lg:col-span-2 space-y-6">
                    <div>
                      <label className="block text-sm font-medium text-slate-700 mb-1">Email Subject <span className="text-red-500">*</span></label>
                      <input type="text" maxLength={LIMITS.emailSubject} value={formData.emailSubject} onChange={e => setFormData({...formData, emailSubject: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.emailSubject ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                      {errors.emailSubject && <p className="text-red-500 text-xs mt-1">{errors.emailSubject}</p>}
                    </div>
                    <div>
                      <div className="flex justify-between items-center mb-1">
                        <label className="block text-sm font-medium text-slate-700">Email Body (HTML Supported) <span className="text-red-500">*</span></label>
                        <span className={`text-xs ${formData.emailBody.length > LIMITS.emailBody ? 'text-red-500' : 'text-slate-500'}`}>
                          {formData.emailBody.length}/{LIMITS.emailBody}
                        </span>
                      </div>
                      <textarea
                        rows={10}
                        maxLength={LIMITS.emailBody}
                        value={formData.emailBody}
                        onChange={e => setFormData({...formData, emailBody: e.target.value})}
                        className={`w-full px-4 py-3 bg-slate-50 border rounded-xl text-sm font-mono focus:outline-none focus:ring-2 transition-all resize-none ${errors.emailBody ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`}
                        placeholder="<p>Dear {{PatientName}},</p>"
                      />
                      {errors.emailBody && <p className="text-red-500 text-xs mt-1">{errors.emailBody}</p>}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 bg-slate-50 border border-slate-100 p-4 rounded-xl">
                      <div className="flex items-center gap-3">
                        <input type="checkbox" id="attachmentAllowed" checked={formData.attachmentAllowed} onChange={e => setFormData({...formData, attachmentAllowed: e.target.checked, attachmentType: e.target.checked ? formData.attachmentType : ''})} className="w-4 h-4 text-primary bg-slate-100 border-slate-300 rounded focus:ring-primary" />
                        <label htmlFor="attachmentAllowed" className="text-sm font-medium text-slate-700">Attachment Allowed</label>
                      </div>
                      {formData.attachmentAllowed && (
                        <div>
                          <label className="block text-xs font-medium text-slate-500 mb-1">Attachment Type <span className="text-red-500">*</span></label>
                          <select value={formData.attachmentType} onChange={e => setFormData({...formData, attachmentType: e.target.value})} className={`w-full px-3 py-1.5 bg-white border rounded text-sm focus:outline-none focus:ring-1 ${errors.attachmentType ? 'border-red-300 focus:ring-red-300' : 'border-slate-200 focus:ring-primary'}`}>
                            <option value="">Select Type</option>
                            {ATTACHMENT_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                          </select>
                          {errors.attachmentType && <p className="text-red-500 text-xs mt-1">{errors.attachmentType}</p>}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Variables Helper */}
                  <div className="bg-slate-50 border border-slate-100 rounded-2xl p-5">
                    <h4 className="text-sm font-bold text-slate-700 mb-3">Supported Variables</h4>
                    <p className="text-xs text-slate-500 mb-4">Click to insert a variable into the Email Body.</p>
                    <div className="flex flex-wrap gap-2">
                      {VARIABLES.map((variable) => (
                        <button
                          key={variable}
                          type="button"
                          onClick={() => insertVariable(variable)}
                          className="px-2 py-1 bg-white border border-slate-200 rounded text-xs font-mono text-primary hover:border-primary hover:bg-primary/5 transition-colors"
                        >
                          {variable}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </section>

              {/* System Information */}
              <section>
                <h3 className="text-lg font-bold text-slate-800 mb-4 border-b border-slate-100 pb-2">System Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Status <span className="text-red-500">*</span></label>
                    <select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Remarks</label>
                    <input type="text" maxLength={LIMITS.remarks} value={formData.remarks} onChange={e => setFormData({...formData, remarks: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

            </div>

            <div className="p-4 border-t border-slate-100 bg-slate-50/50 flex justify-between items-center shrink-0">
              <Button variant="outline" color="secondary" onClick={() => setFormData(emptyData)} icon={RefreshCw}>
                Reset
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" color="secondary" onClick={() => { setIsFormOpen(false); setSelectedRecord(null); }}>
                  Cancel
                </Button>
                <Button variant="filled" color="primary" onClick={handleSaveForm} icon={Save} disabled={isSaving}>
                  {isSaving ? 'Saving…' : selectedRecord ? 'Update' : 'Save'}
                </Button>
              </div>
            </div>
          </div>
        </>
      )}

      <Modal
        isOpen={isDeleteOpen}
        onClose={() => setIsDeleteOpen(false)}
        title="Confirm Deletion"
        maxWidth="sm"
      >
        <div className="p-1">
          <div className="flex items-center gap-4 mb-6 text-amber-600 bg-amber-50 p-4 rounded-xl">
            <AlertTriangle className="w-8 h-8 shrink-0" />
            <p className="text-sm font-medium">
              Are you sure you want to delete Template <strong>{selectedRecord?.templateCode}</strong>?
              This action cannot be undone.
            </p>
          </div>
          <div className="flex justify-end gap-3">
            <Button variant="outline" color="secondary" onClick={() => setIsDeleteOpen(false)}>
              Cancel
            </Button>
            <Button variant="filled" color="danger" onClick={confirmDelete}>
              Confirm Delete
            </Button>
          </div>
        </div>
      </Modal>
    </motion.div>
  );
};
