import { useState, useEffect } from 'react';
import { Pagination } from '@/components/ui/Pagination';
import { usePagination } from '@/hooks/usePagination';
import {
  Plus, Search, Filter, Download, Edit2, Trash2, AlertTriangle,
  Save, RefreshCw, CalendarClock, X
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '../../../components/ui/Button';
import { Modal } from '../../../components/ui/Modal';
import { exportToExcel } from '../../../utils/exportToExcel';

const API_BASE = import.meta.env.VITE_API_URL as string;

interface ReminderRuleRecord {
  id: number;
  ruleCode: string;
  ruleName: string;
  module: string;
  event: string;
  triggerBefore: string;
  notificationChannel: string;
  repeatReminder: boolean;
  repeatFrequency: string;
  maxRetryCount: number;
  recipientPatient: boolean;
  recipientDoctor: boolean;
  recipientStaff: boolean;
  recipientAttender: boolean;
  status: string;
  remarks: string;
  createdBy?: string;
  createdDate?: string;
  updatedBy?: string;
  updatedDate?: string;
}

// RuleCode is auto-generated by the backend (RR-001 format)
type ReminderRuleForm = Omit<ReminderRuleRecord, 'id' | 'ruleCode' | 'createdBy' | 'createdDate' | 'updatedBy' | 'updatedDate'>;

const emptyData: ReminderRuleForm = {
  ruleName: '',
  module: '',
  event: '',
  triggerBefore: '',
  notificationChannel: 'SMS',
  repeatReminder: false,
  repeatFrequency: '',
  maxRetryCount: 1,
  recipientPatient: true,
  recipientDoctor: false,
  recipientStaff: false,
  recipientAttender: false,
  status: 'Active',
  remarks: ''
};

const LIMITS = {
  ruleName: 150, module: 100, event: 100,
  triggerBefore: 100, repeatFrequency: 100, remarks: 500,
  retryMin: 1, retryMax: 10,
};

const MODULES = ['Appointment', 'Billing', 'Pharmacy', 'Laboratory'];
const EVENTS = ['Appointment Due', 'Bill Overdue', 'Follow-up Due'];
const CHANNELS = [
  { value: 'SMS', label: 'SMS' },
  { value: 'Email', label: 'Email' },
  { value: 'WhatsApp', label: 'WhatsApp' },
  { value: 'Push', label: 'Push Notification' },
];

const mapApiToRecord = (item: Record<string, unknown>): ReminderRuleRecord => ({
  id:                  item.id                  as number,
  ruleCode:            item.ruleCode            as string,
  ruleName:            item.ruleName            as string,
  module:              item.module              as string,
  event:               item.event               as string,
  triggerBefore:       item.triggerBefore       as string,
  notificationChannel: item.notificationChannel as string,
  repeatReminder:      Boolean(item.repeatReminder),
  repeatFrequency:     (item.repeatFrequency     as string) ?? '',
  maxRetryCount:       (item.maxRetryCount       as number) ?? 1,
  recipientPatient:    Boolean(item.recipientPatient),
  recipientDoctor:     Boolean(item.recipientDoctor),
  recipientStaff:      Boolean(item.recipientStaff),
  recipientAttender:   Boolean(item.recipientAttender),
  status:              item.status              as string,
  remarks:             (item.remarks             as string) ?? '',
  createdBy:           (item.createdBy           as string) ?? undefined,
  createdDate:         item.createdDate ? String(item.createdDate).split('T')[0] : undefined,
  updatedBy:           (item.updatedBy           as string) ?? undefined,
  updatedDate:         item.updatedDate ? String(item.updatedDate).split('T')[0] : undefined,
});

export const ReminderRuleMaster = () => {
  const [records, setRecords] = useState<ReminderRuleRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [nextCode, setNextCode] = useState('');

  // Filter States
  const [showFilters, setShowFilters] = useState(false);
  const [filterModule, setFilterModule] = useState('');
  const [filterChannel, setFilterChannel] = useState('');
  const [filterStatus, setFilterStatus] = useState('');

  // Form States
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState<ReminderRuleRecord | null>(null);
  const [formData, setFormData] = useState<ReminderRuleForm>(emptyData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // ── Fetch rules ──────────────────────────────────────────────
  const fetchRules = async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/reminder-rules/`);
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data: Record<string, unknown>[] = await res.json();
      setRecords(data.map(mapApiToRecord));
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Failed to load reminder rules');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchRules(); }, []);

  const fetchNextCode = async () => {
    setNextCode('');
    try {
      const res = await fetch(`${API_BASE}/reminder-rules/next-code`);
      if (res.ok) setNextCode((await res.json()).ruleCode ?? '');
    } catch { setNextCode(''); }
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.ruleName.trim()) newErrors.ruleName = 'Rule Name is required';
    if (!formData.module.trim()) newErrors.module = 'Module is required';
    if (!formData.event.trim()) newErrors.event = 'Trigger Event is required';
    if (!formData.triggerBefore.trim()) newErrors.triggerBefore = 'Trigger time is required';

    // At least one recipient must be selected
    if (!(formData.recipientPatient || formData.recipientDoctor || formData.recipientStaff || formData.recipientAttender))
      newErrors.recipients = 'Select at least one recipient';

    // Repeat rules
    if (formData.repeatReminder) {
      if (!formData.repeatFrequency.trim()) newErrors.repeatFrequency = 'Repeat Frequency is required';
      if (formData.maxRetryCount < LIMITS.retryMin || formData.maxRetryCount > LIMITS.retryMax)
        newErrors.maxRetryCount = `Between ${LIMITS.retryMin} and ${LIMITS.retryMax}`;
    }

    // Client-side hint (server is the source of truth)
    if (records.some(r => r.ruleName.toLowerCase() === formData.ruleName.trim().toLowerCase() && r.id !== selectedRecord?.id))
      newErrors.ruleName = 'Rule Name must be unique';

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleCreateNew = () => {
    setSelectedRecord(null);
    setFormData(emptyData);
    setErrors({});
    setIsFormOpen(true);
    fetchNextCode();
  };

  const handleEdit = (record: ReminderRuleRecord) => {
    setSelectedRecord(record);
    const { id, ruleCode, createdBy, createdDate, updatedBy, updatedDate, ...rest } = record;
    setFormData(rest);
    setErrors({});
    setIsFormOpen(true);
  };

  const handleDeleteRequest = (record: ReminderRuleRecord) => {
    setSelectedRecord(record);
    setIsDeleteOpen(true);
  };

  const handleSaveForm = async () => {
    if (!validateForm()) return;
    setIsSaving(true);
    setApiError(null);
    try {
      const body = {
        ruleName:            formData.ruleName.trim(),
        module:              formData.module,
        event:               formData.event,
        triggerBefore:       formData.triggerBefore.trim(),
        notificationChannel: formData.notificationChannel,
        repeatReminder:      formData.repeatReminder,
        repeatFrequency:     formData.repeatReminder ? (formData.repeatFrequency || null) : null,
        maxRetryCount:       formData.repeatReminder ? formData.maxRetryCount : 1,
        recipientPatient:    formData.recipientPatient,
        recipientDoctor:     formData.recipientDoctor,
        recipientStaff:      formData.recipientStaff,
        recipientAttender:   formData.recipientAttender,
        status:              formData.status,
        remarks:             formData.remarks || null,
      };

      let res: Response;
      if (selectedRecord) {
        res = await fetch(`${API_BASE}/reminder-rules/${selectedRecord.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, updatedBy: 'Admin' }),
        });
      } else {
        res = await fetch(`${API_BASE}/reminder-rules/`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, createdBy: 'Admin' }),
        });
      }
      if (!res.ok) {
        const data = await res.json().catch(() => null);
        let detail = `Save failed: ${res.status}`;
        if (data && typeof data.detail === 'string') detail = data.detail;
        else if (data && Array.isArray(data.detail) && data.detail[0]?.msg) detail = data.detail[0].msg;
        throw new Error(detail);
      }

      await fetchRules();
      setIsFormOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setIsSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!selectedRecord) return;
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/reminder-rules/${selectedRecord.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`Delete failed: ${res.status}`);
      await fetchRules();
      setIsDeleteOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Delete failed');
      setIsDeleteOpen(false);
    }
  };

  const filteredRecords = records.filter(record => {
    const matchesSearch =
      record.ruleName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.ruleCode.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesModule = !filterModule || record.module === filterModule;
    const matchesChannel = !filterChannel || record.notificationChannel === filterChannel;
    const matchesStatus = !filterStatus || record.status === filterStatus;
    return matchesSearch && matchesModule && matchesChannel && matchesStatus;
  });

  const uniqueModules = Array.from(new Set([...MODULES, ...records.map(r => r.module)].filter(Boolean)));

  const _totalPages = Math.max(1, Math.ceil(filteredRecords.length / itemsPerPage));
  const _page = Math.min(currentPage, _totalPages);
  const pagedRecords = filteredRecords.slice((_page - 1) * itemsPerPage, _page * itemsPerPage);

  const { page, setPage, pageSize, total, paged } = usePagination(MODULES);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="h-full flex flex-col relative"
    >
      {apiError && (
        <div className="mb-4 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span className="flex-1">{apiError}</span>
          <button onClick={() => setApiError(null)} className="text-red-500 hover:text-red-700 font-medium">Dismiss</button>
        </div>
      )}

      {!isFormOpen ? (
        <>
          <div className="flex items-center justify-between mb-4">
            <div>
              <h1 className="text-3xl font-bold text-slate-800">Reminder Rule</h1>
            </div>
            <div className="flex gap-3">
              <Button variant="filled" color="primary" icon={Plus} onClick={handleCreateNew}>
                Add Rule
              </Button>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex flex-wrap gap-4 items-center justify-between">
              <div className="relative flex-1 max-w-md">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search by Code or Name..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary text-sm"
                />
              </div>
              <div className="flex items-center gap-2">
              <button onClick={() => setShowFilters(!showFilters)} title="Filters" className={showFilters ? "p-2 border rounded-lg transition-colors border-primary bg-primary/5 text-primary" : "p-2 border rounded-lg transition-colors border-slate-200 text-slate-500 hover:bg-slate-50"}>
                <Filter className="w-4 h-4" />
              </button>
              <button onClick={() => { setSearchTerm(''); setFilterChannel(''); setFilterModule(''); setFilterStatus(''); }} title="Clear search & filters" className="p-2 border border-red-200 rounded-lg text-red-500 hover:bg-red-50 hover:border-red-300 transition-colors">
                <X className="w-4 h-4" />
              </button>
              <button onClick={() => exportToExcel(records, 'ReminderRuleMaster')} title="Export to Excel" className="p-2 border border-emerald-200 rounded-lg text-emerald-600 hover:bg-emerald-50 hover:border-emerald-300 transition-colors">
                <Download className="w-4 h-4" />
              </button>
            </div>
            </div>

            <AnimatePresence>
              {showFilters && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="border-b border-slate-200 bg-slate-50/50 p-4"
                >
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <select
                      value={filterModule}
                      onChange={(e) => setFilterModule(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Modules</option>
                      {uniqueModules.map(m => <option key={m} value={m}>{m}</option>)}
                    </select>
                    <select
                      value={filterChannel}
                      onChange={(e) => setFilterChannel(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Channels</option>
                      <option value="SMS">SMS</option>
                      <option value="Email">Email</option>
                      <option value="WhatsApp">WhatsApp</option>
                      <option value="Push">Push</option>
                    </select>
                    <select
                      value={filterStatus}
                      onChange={(e) => setFilterStatus(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Statuses</option>
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="flex-1 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600">
                  <tr>
                    <th className="px-4 py-3 font-medium">Rule Code</th>
                    <th className="px-4 py-3 font-medium">Rule Name</th>
                    <th className="px-4 py-3 font-medium">Module</th>
                    <th className="px-4 py-3 font-medium">Channel</th>
                    <th className="px-4 py-3 font-medium text-center">Status</th>
                    <th className="px-4 py-3 font-medium text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {isLoading ? (
                    <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">Loading rules…</td></tr>
                  ) : filteredRecords.length > 0 ? (
                    pagedRecords.map((record) => (
                      <tr key={record.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-3 font-medium text-slate-800">{record.ruleCode}</td>
                        <td className="px-4 py-3 font-medium text-primary">{record.ruleName}</td>
                        <td className="px-4 py-3 text-slate-600">{record.module}</td>
                        <td className="px-4 py-3 text-slate-600">
                          <span className={`inline-flex px-2 py-1 rounded-md text-xs font-medium border
                            ${record.notificationChannel === 'WhatsApp' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : ''}
                            ${record.notificationChannel === 'Email' ? 'bg-purple-50 text-purple-700 border-purple-200' : ''}
                            ${record.notificationChannel === 'SMS' ? 'bg-amber-50 text-amber-700 border-amber-200' : ''}
                            ${record.notificationChannel === 'Push' ? 'bg-blue-50 text-blue-700 border-blue-200' : ''}
                          `}>
                            {record.notificationChannel}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${
                            record.status === 'Active'
                              ? 'bg-emerald-50 text-emerald-600 border border-emerald-200'
                              : 'bg-red-50 text-red-600 border border-red-200'
                          }`}>
                            {record.status}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => handleEdit(record)}
                              className="p-1.5 text-slate-400 hover:text-primary hover:bg-primary/5 rounded-lg transition-colors"
                              title="Edit"
                            >
                              <Edit2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteRequest(record)}
                              className="p-1.5 text-red-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={6} className="px-4 py-8 text-center text-slate-500">
                        No rules found matching your criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
        <Pagination page={page} pageSize={pageSize} totalItems={total} onPageChange={setPage} />
            <div className="flex flex-wrap items-center justify-between gap-3 p-4 border-t border-slate-100 text-sm text-slate-500">
              <div className="flex items-center gap-2">
                <span>Show</span>
                <select value={itemsPerPage} onChange={(e) => { setItemsPerPage(Number(e.target.value)); setCurrentPage(1); }} className="px-2 py-1 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                  <option value={10}>10</option>
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>
                <span>entries</span>
                <span className="text-slate-400">· {filteredRecords.length} total</span>
              </div>
              <div className="flex items-center gap-3">
                <span>Page {_page} of {_totalPages}</span>
                <div className="flex gap-1">
                  <button onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={_page <= 1} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Prev</button>
                  <button onClick={() => setCurrentPage(p => Math.min(_totalPages, p + 1))} disabled={_page >= _totalPages} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Next</button>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : (
        <>
          <div className="flex justify-between items-center mb-2">
            <div>
              <h1 className="text-2xl font-bold text-slate-800">
                {selectedRecord ? `Edit Rule: ${selectedRecord.ruleName}` : 'Add Reminder Rule'}
              </h1>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="flex-1 overflow-y-auto p-6 space-y-4">

              {/* Basic Information */}
              <section>
                <h3 className="text-lg font-bold text-slate-800 mb-4 border-b border-slate-100 pb-2">Basic Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Rule Code</label>
                    <input type="text" value={selectedRecord ? selectedRecord.ruleCode : (nextCode || 'Auto-generated')} readOnly className="w-full px-4 py-2 bg-slate-100 border border-slate-200 rounded-xl text-sm text-slate-500 cursor-not-allowed focus:outline-none" />
                  </div>
                  <div className="lg:col-span-3">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Rule Name <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.ruleName} value={formData.ruleName} onChange={e => setFormData({...formData, ruleName: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.ruleName ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.ruleName && <p className="text-red-500 text-xs mt-1">{errors.ruleName}</p>}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Module <span className="text-red-500">*</span></label>
                    <select value={formData.module} onChange={e => setFormData({...formData, module: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.module ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`}>
                      <option value="">Select Module</option>
                      {paged.map(m => <option key={m} value={m}>{m}</option>)}
                    </select>
                    {errors.module && <p className="text-red-500 text-xs mt-1">{errors.module}</p>}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Trigger Event <span className="text-red-500">*</span></label>
                    <select value={formData.event} onChange={e => setFormData({...formData, event: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.event ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`}>
                      <option value="">Select Event</option>
                      {EVENTS.map(ev => <option key={ev} value={ev}>{ev}</option>)}
                    </select>
                    {errors.event && <p className="text-red-500 text-xs mt-1">{errors.event}</p>}
                  </div>
                </div>
              </section>

              {/* Reminder Configuration */}
              <section>
                <div className="flex items-center gap-2 mb-4 border-b border-slate-100 pb-2">
                  <CalendarClock className="w-5 h-5 text-amber-500" />
                  <h3 className="text-lg font-bold text-slate-800">Reminder Configuration</h3>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Trigger Before <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.triggerBefore} value={formData.triggerBefore} onChange={e => setFormData({...formData, triggerBefore: e.target.value})} placeholder="e.g. 24 Hours, 30 Minutes" className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.triggerBefore ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.triggerBefore && <p className="text-red-500 text-xs mt-1">{errors.triggerBefore}</p>}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Notification Channel <span className="text-red-500">*</span></label>
                    <select value={formData.notificationChannel} onChange={e => setFormData({...formData, notificationChannel: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                      {CHANNELS.map(ch => <option key={ch.value} value={ch.value}>{ch.label}</option>)}
                    </select>
                  </div>

                  <div className="lg:col-span-4 grid grid-cols-1 md:grid-cols-3 gap-6 bg-slate-50 border border-slate-100 p-5 rounded-2xl">
                    <div className="flex items-center gap-3">
                      <input type="checkbox" id="repeatReminder" checked={formData.repeatReminder} onChange={e => setFormData({...formData, repeatReminder: e.target.checked, repeatFrequency: e.target.checked ? formData.repeatFrequency : '', maxRetryCount: e.target.checked ? formData.maxRetryCount : 1})} className="w-4 h-4 text-primary bg-slate-100 border-slate-300 rounded focus:ring-primary" />
                      <label htmlFor="repeatReminder" className="text-sm font-medium text-slate-700">Repeat Reminder</label>
                    </div>
                    {formData.repeatReminder && (
                      <>
                        <div>
                          <label className="block text-xs font-medium text-slate-500 mb-1">Repeat Frequency <span className="text-red-500">*</span></label>
                          <input type="text" maxLength={LIMITS.repeatFrequency} value={formData.repeatFrequency} onChange={e => setFormData({...formData, repeatFrequency: e.target.value})} placeholder="e.g. Every 1 Hour" className={`w-full px-3 py-1.5 bg-white border rounded text-sm focus:outline-none focus:ring-1 ${errors.repeatFrequency ? 'border-red-300 focus:ring-red-300' : 'border-slate-200 focus:ring-primary'}`} />
                          {errors.repeatFrequency && <p className="text-red-500 text-xs mt-1">{errors.repeatFrequency}</p>}
                        </div>
                        <div>
                          <label className="block text-xs font-medium text-slate-500 mb-1">Max Retry Count</label>
                          <input type="number" min={LIMITS.retryMin} max={LIMITS.retryMax} value={formData.maxRetryCount} onChange={e => setFormData({...formData, maxRetryCount: parseInt(e.target.value) || 1})} className={`w-full px-3 py-1.5 bg-white border rounded text-sm focus:outline-none focus:ring-1 ${errors.maxRetryCount ? 'border-red-300 focus:ring-red-300' : 'border-slate-200 focus:ring-primary'}`} />
                          {errors.maxRetryCount && <p className="text-red-500 text-xs mt-1">{errors.maxRetryCount}</p>}
                        </div>
                      </>
                    )}
                  </div>
                </div>
              </section>

              {/* Recipient Configuration */}
              <section>
                <h3 className="text-lg font-bold text-slate-800 mb-4 border-b border-slate-100 pb-2">Recipient Configuration <span className="text-red-500">*</span></h3>
                <div className="flex flex-wrap gap-8">
                  <div className="flex items-center gap-3">
                    <input type="checkbox" id="recipientPatient" checked={formData.recipientPatient} onChange={e => setFormData({...formData, recipientPatient: e.target.checked})} className="w-5 h-5 text-primary bg-slate-100 border-slate-300 rounded focus:ring-primary" />
                    <label htmlFor="recipientPatient" className="text-sm font-medium text-slate-700">Patient</label>
                  </div>
                  <div className="flex items-center gap-3">
                    <input type="checkbox" id="recipientDoctor" checked={formData.recipientDoctor} onChange={e => setFormData({...formData, recipientDoctor: e.target.checked})} className="w-5 h-5 text-primary bg-slate-100 border-slate-300 rounded focus:ring-primary" />
                    <label htmlFor="recipientDoctor" className="text-sm font-medium text-slate-700">Doctor</label>
                  </div>
                  <div className="flex items-center gap-3">
                    <input type="checkbox" id="recipientStaff" checked={formData.recipientStaff} onChange={e => setFormData({...formData, recipientStaff: e.target.checked})} className="w-5 h-5 text-primary bg-slate-100 border-slate-300 rounded focus:ring-primary" />
                    <label htmlFor="recipientStaff" className="text-sm font-medium text-slate-700">Staff</label>
                  </div>
                  <div className="flex items-center gap-3">
                    <input type="checkbox" id="recipientAttender" checked={formData.recipientAttender} onChange={e => setFormData({...formData, recipientAttender: e.target.checked})} className="w-5 h-5 text-primary bg-slate-100 border-slate-300 rounded focus:ring-primary" />
                    <label htmlFor="recipientAttender" className="text-sm font-medium text-slate-700">Attender</label>
                  </div>
                </div>
                {errors.recipients && <p className="text-red-500 text-xs mt-2">{errors.recipients}</p>}
              </section>

              {/* System Information */}
              <section>
                <h3 className="text-lg font-bold text-slate-800 mb-4 border-b border-slate-100 pb-2">System Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Status <span className="text-red-500">*</span></label>
                    <select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Remarks</label>
                    <input type="text" maxLength={LIMITS.remarks} value={formData.remarks} onChange={e => setFormData({...formData, remarks: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

            </div>

            <div className="p-4 border-t border-slate-100 bg-slate-50/50 flex justify-between items-center shrink-0">
              <Button variant="outline" color="secondary" onClick={() => setFormData(emptyData)} icon={RefreshCw}>
                Reset
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" color="secondary" onClick={() => { setIsFormOpen(false); setSelectedRecord(null); }}>
                  Cancel
                </Button>
                <Button variant="filled" color="primary" onClick={handleSaveForm} icon={Save} disabled={isSaving}>
                  {isSaving ? 'Saving…' : selectedRecord ? 'Update' : 'Save'}
                </Button>
              </div>
            </div>
          </div>
        </>
      )}

      <Modal
        isOpen={isDeleteOpen}
        onClose={() => setIsDeleteOpen(false)}
        title="Confirm Deletion"
        maxWidth="sm"
      >
        <div className="p-1">
          <div className="flex items-center gap-4 mb-6 text-amber-600 bg-amber-50 p-4 rounded-xl">
            <AlertTriangle className="w-8 h-8 shrink-0" />
            <p className="text-sm font-medium">
              Are you sure you want to delete Rule <strong>{selectedRecord?.ruleCode}</strong>?
              This action cannot be undone.
            </p>
          </div>
          <div className="flex justify-end gap-3">
            <Button variant="outline" color="secondary" onClick={() => setIsDeleteOpen(false)}>
              Cancel
            </Button>
            <Button variant="filled" color="danger" onClick={confirmDelete}>
              Confirm Delete
            </Button>
          </div>
        </div>
      </Modal>
    </motion.div>
  );
};


