import { useState, useEffect, type KeyboardEvent } from 'react';
import {
  Plus, Search, Filter, Download, Edit2, Trash2, AlertTriangle,
  Save, RefreshCw, X
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '../../../components/ui/Button';
import { Modal } from '../../../components/ui/Modal';
import { exportToExcel } from '../../../utils/exportToExcel';

const API_BASE = import.meta.env.VITE_API_URL as string;

interface ServiceRecord {
  id: number;
  serviceCode: string;
  serviceName: string;
  serviceCategory: string;
  department: string;
  description: string;
  standardPrice: number;
  costPrice: number;
  taxApplicable: boolean;
  tax: string;
  allowDiscount: boolean;
  requiresDoctorApproval: boolean;
  availableForOp: boolean;
  availableForIp: boolean;
  availableForEmergency: boolean;
  status: string;
  remarks: string;
  createdBy?: string;
  createdDate?: string;
  updatedBy?: string;
  updatedDate?: string;
}

// ServiceCode is auto-generated by the backend (SRV-001 format)
type ServiceForm = Omit<ServiceRecord, 'id' | 'serviceCode' | 'createdBy' | 'createdDate' | 'updatedBy' | 'updatedDate'>;

const emptyData: ServiceForm = {
  serviceName: '',
  serviceCategory: '',
  department: '',
  description: '',
  standardPrice: 0,
  costPrice: 0,
  taxApplicable: false,
  tax: '',
  allowDiscount: false,
  requiresDoctorApproval: false,
  availableForOp: false,
  availableForIp: false,
  availableForEmergency: false,
  status: 'Active',
  remarks: ''
};

// Field limits (aligned with backend schema + DB column sizes)
const LIMITS = {
  serviceName: 150,
  serviceCategory: 100,
  department: 100,
  description: 500,
  remarks: 500,
  priceMax: 9999999,
};

// Block characters invalid inside a decimal <input type="number">.
const blockDecimalKeys = (e: KeyboardEvent<HTMLInputElement>) => {
  if (['e', 'E', '+', '-'].includes(e.key)) e.preventDefault();
};

const mapApiToRecord = (item: Record<string, unknown>): ServiceRecord => ({
  id:                     item.id                     as number,
  serviceCode:            item.serviceCode            as string,
  serviceName:            item.serviceName            as string,
  serviceCategory:        item.serviceCategory        as string,
  department:             item.department             as string,
  description:            (item.description           as string) ?? '',
  standardPrice:          Number(item.standardPrice ?? 0),
  costPrice:              item.costPrice != null ? Number(item.costPrice) : 0,
  taxApplicable:          Boolean(item.taxApplicable),
  tax:                    (item.tax                   as string) ?? '',
  allowDiscount:          Boolean(item.allowDiscount),
  requiresDoctorApproval: Boolean(item.requiresDoctorApproval),
  availableForOp:         Boolean(item.availableForOp),
  availableForIp:         Boolean(item.availableForIp),
  availableForEmergency:  Boolean(item.availableForEmergency),
  status:                 item.status                 as string,
  remarks:                (item.remarks               as string) ?? '',
  createdBy:              (item.createdBy             as string) ?? undefined,
  createdDate:            item.createdDate ? String(item.createdDate).split('T')[0] : undefined,
  updatedBy:              (item.updatedBy             as string) ?? undefined,
  updatedDate:            item.updatedDate ? String(item.updatedDate).split('T')[0] : undefined,
});

export const ServiceMaster = () => {
  const [records, setRecords] = useState<ServiceRecord[]>([]);
  const [taxes, setTaxes] = useState<{id: number, gstPercentage: number}[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [nextCode, setNextCode] = useState('');

  // Filter States
  const [showFilters, setShowFilters] = useState(false);
  const [filterDepartment, setFilterDepartment] = useState('');
  const [filterCategory, setFilterCategory] = useState('');
  const [filterStatus, setFilterStatus] = useState('');

  // Form States
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState<ServiceRecord | null>(null);
  const [formData, setFormData] = useState<ServiceForm>(emptyData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // ── Fetch services ───────────────────────────────────────────
  const fetchServices = async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/services/`);
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data: Record<string, unknown>[] = await res.json();
      setRecords(data.map(mapApiToRecord));
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Failed to load services');
    } finally {
      setIsLoading(false);
    }
  };

  const fetchTaxes = async () => {
    try {
      const res = await fetch(`${API_BASE}/taxes/`);
      if (res.ok) {
        const data = await res.json();
        setTaxes(data.filter((t: any) => t.status === 'Active'));
      }
    } catch (err) {
      console.error('Failed to fetch taxes', err);
    }
  };

  useEffect(() => { 
    fetchServices();
    fetchTaxes();
  }, []);

  const fetchNextCode = async () => {
    setNextCode('');
    try {
      const res = await fetch(`${API_BASE}/services/next-code`);
      if (res.ok) {
        const data = await res.json();
        setNextCode(data.serviceCode ?? '');
      }
    } catch {
      setNextCode('');
    }
  };

  const departments = Array.from(new Set(records.map(r => r.department))).sort();
  const categories = Array.from(new Set(records.map(r => r.serviceCategory))).sort();

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.serviceName.trim()) newErrors.serviceName = 'Service Name is required';
    if (!formData.serviceCategory.trim()) newErrors.serviceCategory = 'Category is required';

    if (formData.standardPrice <= 0) newErrors.standardPrice = 'Price must be greater than zero';
    else if (formData.standardPrice > LIMITS.priceMax) newErrors.standardPrice = 'Price is too large';

    if (formData.taxApplicable && !formData.tax.trim()) newErrors.tax = 'Tax selection is required when Tax is applicable';

    // Name uniqueness (Service Code is auto-generated)
    if (records.some(r => r.serviceName.toLowerCase() === formData.serviceName.trim().toLowerCase() && r.id !== selectedRecord?.id)) {
      newErrors.serviceName = 'Service Name cannot be duplicated';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleCreateNew = () => {
    setSelectedRecord(null);
    setFormData(emptyData);
    setErrors({});
    setIsFormOpen(true);
    fetchNextCode();
  };

  const handleEdit = (record: ServiceRecord) => {
    setSelectedRecord(record);
    const { id, serviceCode, createdBy, createdDate, updatedBy, updatedDate, ...rest } = record;
    setFormData(rest);
    setErrors({});
    setIsFormOpen(true);
  };

  const handleDeleteRequest = (record: ServiceRecord) => {
    setSelectedRecord(record);
    setIsDeleteOpen(true);
  };

  const handleSaveForm = async () => {
    if (!validateForm()) return;
    setIsSaving(true);
    setApiError(null);
    try {
      const body = {
        serviceName:            formData.serviceName.trim(),
        serviceCategory:        formData.serviceCategory.trim(),
        department:             "",
        description:            formData.description || null,
        standardPrice:          formData.standardPrice,
        costPrice:              0,
        taxApplicable:          formData.taxApplicable,
        tax:                    formData.taxApplicable ? (formData.tax || null) : null,
        allowDiscount:          formData.allowDiscount,
        requiresDoctorApproval: formData.requiresDoctorApproval,
        availableForOp:         formData.availableForOp,
        availableForIp:         formData.availableForIp,
        availableForEmergency:  formData.availableForEmergency,
        status:                 formData.status,
        remarks:                formData.remarks || null,
      };

      let res: Response;
      if (selectedRecord) {
        res = await fetch(`${API_BASE}/services/${selectedRecord.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, updatedBy: 'Admin' }),
        });
      } else {
        res = await fetch(`${API_BASE}/services/`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, createdBy: 'Admin' }),
        });
      }
      if (!res.ok) {
        const data = await res.json().catch(() => null);
        const detail = data && typeof data.detail === 'string' ? data.detail : `Save failed: ${res.status}`;
        throw new Error(detail);
      }

      await fetchServices();
      setIsFormOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setIsSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!selectedRecord) return;
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/services/${selectedRecord.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`Delete failed: ${res.status}`);
      await fetchServices();
      setIsDeleteOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Delete failed');
      setIsDeleteOpen(false);
    }
  };

  const filteredRecords = records.filter(record => {
    const matchesSearch =
      record.serviceName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.serviceCode.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesDept = !filterDepartment || record.department === filterDepartment;
    const matchesCategory = !filterCategory || record.serviceCategory === filterCategory;
    const matchesStatus = !filterStatus || record.status === filterStatus;

    return matchesSearch && matchesDept && matchesCategory && matchesStatus;
  });

  const _totalPages = Math.max(1, Math.ceil(filteredRecords.length / itemsPerPage));
  const _page = Math.min(currentPage, _totalPages);
  const pagedRecords = filteredRecords.slice((_page - 1) * itemsPerPage, _page * itemsPerPage);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="h-full flex flex-col relative"
    >
      {apiError && (
        <div className="mb-4 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span className="flex-1">{apiError}</span>
          <button onClick={() => setApiError(null)} className="text-red-500 hover:text-red-700 font-medium">Dismiss</button>
        </div>
      )}

      {!isFormOpen ? (
        <>
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-slate-800">Service Master</h1>
              <p className="text-slate-500 mt-1"></p>
            </div>
            <div className="flex gap-3">
              <Button variant="filled" color="primary" icon={Plus} onClick={handleCreateNew}>
                Add Service
              </Button>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex flex-wrap gap-4 items-center justify-between">
              <div className="relative flex-1 max-w-md">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search by Service Name or Code..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary text-sm"
                />
              </div>
              <div className="flex items-center gap-2">
              <button onClick={() => setShowFilters(!showFilters)} title="Filters" className={showFilters ? "p-2 border rounded-lg transition-colors border-primary bg-primary/5 text-primary" : "p-2 border rounded-lg transition-colors border-slate-200 text-slate-500 hover:bg-slate-50"}>
                <Filter className="w-4 h-4" />
              </button>
              <button onClick={() => { setSearchTerm(''); setFilterCategory(''); setFilterDepartment(''); setFilterStatus(''); }} title="Clear search & filters" className="p-2 border border-red-200 rounded-lg text-red-500 hover:bg-red-50 hover:border-red-300 transition-colors">
                <X className="w-4 h-4" />
              </button>
              <button onClick={() => exportToExcel(records, 'ServiceMaster')} title="Export to Excel" className="p-2 border border-emerald-200 rounded-lg text-emerald-600 hover:bg-emerald-50 hover:border-emerald-300 transition-colors">
                <Download className="w-4 h-4" />
              </button>
            </div>
            </div>

            <AnimatePresence>
              {showFilters && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="border-b border-slate-200 bg-slate-50/50 p-4"
                >
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <select
                      value={filterDepartment}
                      onChange={(e) => setFilterDepartment(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Departments</option>
                      {departments.map(d => <option key={d} value={d}>{d}</option>)}
                    </select>
                    <select
                      value={filterCategory}
                      onChange={(e) => setFilterCategory(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Categories</option>
                      {categories.map(c => <option key={c} value={c}>{c}</option>)}
                    </select>
                    <select
                      value={filterStatus}
                      onChange={(e) => setFilterStatus(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Statuses</option>
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="flex-1 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600">
                  <tr>
                    <th className="px-4 py-3 font-medium">Service Code</th>
                    <th className="px-4 py-3 font-medium">Service Name</th>
                    <th className="px-4 py-3 font-medium">Department</th>
                    <th className="px-4 py-3 font-medium">Category</th>
                    <th className="px-4 py-3 font-medium">Price</th>
                    <th className="px-4 py-3 font-medium text-center">Status</th>
                    <th className="px-4 py-3 font-medium text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {isLoading ? (
                    <tr>
                      <td colSpan={7} className="px-4 py-8 text-center text-slate-500">
                        Loading services...
                      </td>
                    </tr>
                  ) : filteredRecords.length > 0 ? (
                    pagedRecords.map((record) => (
                      <tr key={record.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-3 font-medium text-slate-800">{record.serviceCode}</td>
                        <td className="px-4 py-3 font-medium text-slate-800">{record.serviceName}</td>
                        <td className="px-4 py-3 text-slate-600">{record.department}</td>
                        <td className="px-4 py-3 text-slate-600">
                          <span className="px-2 py-1 bg-slate-100 border border-slate-200 rounded text-xs">
                            {record.serviceCategory}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-slate-800 font-medium">₹{record.standardPrice.toFixed(2)}</td>
                        <td className="px-4 py-3 text-center">
                          <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${
                            record.status === 'Active'
                              ? 'bg-emerald-50 text-emerald-600 border border-emerald-200'
                              : 'bg-red-50 text-red-600 border border-red-200'
                          }`}>
                            {record.status}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => handleEdit(record)}
                              className="p-1.5 text-slate-400 hover:text-primary hover:bg-primary/5 rounded-lg transition-colors"
                              title="Edit"
                            >
                              <Edit2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteRequest(record)}
                              className="p-1.5 text-red-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={7} className="px-4 py-8 text-center text-slate-500">
                        No services found matching your criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            <div className="flex flex-wrap items-center justify-between gap-3 p-4 border-t border-slate-100 text-sm text-slate-500">
              <div className="flex items-center gap-2">
                <span>Show</span>
                <select value={itemsPerPage} onChange={(e) => { setItemsPerPage(Number(e.target.value)); setCurrentPage(1); }} className="px-2 py-1 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                  <option value={10}>10</option>
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>
                <span>entries</span>
                <span className="text-slate-400">· {filteredRecords.length} total</span>
              </div>
              <div className="flex items-center gap-3">
                <span>Page {_page} of {_totalPages}</span>
                <div className="flex gap-1">
                  <button onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={_page <= 1} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Prev</button>
                  <button onClick={() => setCurrentPage(p => Math.min(_totalPages, p + 1))} disabled={_page >= _totalPages} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Next</button>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : (
        <>
          <div className="flex justify-between items-center mb-6">
            <div>
              <h1 className="text-2xl font-bold text-slate-800">
                {selectedRecord ? `Edit Service: ${selectedRecord.serviceName}` : 'Add New Service'}
              </h1>
              <p className="text-slate-500 text-sm">Configure hospital billing service</p>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="flex-1 overflow-y-auto p-5 space-y-4">
              {/* Basic Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Basic Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Service Code</label>
                    <input type="text" value={selectedRecord ? selectedRecord.serviceCode : (nextCode || 'Auto-generating…')} disabled readOnly className="w-full px-4 py-2 bg-slate-100 border border-slate-200 rounded-xl text-sm text-slate-500 cursor-not-allowed" />
                    {!selectedRecord && nextCode && (
                      <p className="text-slate-400 text-xs mt-1">Provisional — final code is assigned on save</p>
                    )}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Service Name <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.serviceName} value={formData.serviceName} onChange={e => setFormData({...formData, serviceName: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.serviceName ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.serviceName && <p className="text-red-500 text-xs mt-1">{errors.serviceName}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Service Category <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.serviceCategory} value={formData.serviceCategory} onChange={e => setFormData({...formData, serviceCategory: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.serviceCategory ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.serviceCategory && <p className="text-red-500 text-xs mt-1">{errors.serviceCategory}</p>}
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Description</label>
                    <input type="text" maxLength={LIMITS.description} value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

              {/* Pricing Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Pricing Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Standard Price <span className="text-red-500">*</span></label>
                    <input type="number" min="0" step="0.01" onKeyDown={blockDecimalKeys} value={formData.standardPrice} onChange={e => setFormData({...formData, standardPrice: Number(e.target.value)})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.standardPrice ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.standardPrice && <p className="text-red-500 text-xs mt-1">{errors.standardPrice}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Tax Selection {formData.taxApplicable && <span className="text-red-500">*</span>}</label>
                    <select disabled={!formData.taxApplicable} value={formData.tax} onChange={e => setFormData({...formData, tax: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.tax ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'} disabled:opacity-50`}>
                      <option value="">Select Tax</option>
                      {taxes.map(t => (
                        <option key={t.id} value={`GST ${t.gstPercentage}%`}>GST {t.gstPercentage}%</option>
                      ))}
                    </select>
                    {errors.tax && <p className="text-red-500 text-xs mt-1">{errors.tax}</p>}
                  </div>
                  <div className="flex items-center gap-2">
                    <input type="checkbox" id="taxApplicable" checked={formData.taxApplicable} onChange={e => setFormData({...formData, taxApplicable: e.target.checked, tax: e.target.checked ? formData.tax : ''})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                    <label htmlFor="taxApplicable" className="text-sm font-medium text-slate-700">Tax Applicable</label>
                  </div>
                </div>
              </section>

              {/* Configuration */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Configuration</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                  <div className="flex items-center gap-2">
                    <input type="checkbox" id="allowDiscount" checked={formData.allowDiscount} onChange={e => setFormData({...formData, allowDiscount: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                    <label htmlFor="allowDiscount" className="text-sm text-slate-700">Allow Discount</label>
                  </div>
                  <div className="flex items-center gap-2">
                    <input type="checkbox" id="requiresDoctorApproval" checked={formData.requiresDoctorApproval} onChange={e => setFormData({...formData, requiresDoctorApproval: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                    <label htmlFor="requiresDoctorApproval" className="text-sm text-slate-700">Requires Doctor Approval</label>
                  </div>
                  <div className="flex items-center gap-2">
                    <input type="checkbox" id="availableForOp" checked={formData.availableForOp} onChange={e => setFormData({...formData, availableForOp: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                    <label htmlFor="availableForOp" className="text-sm text-slate-700">Available for OP</label>
                  </div>
                  <div className="flex items-center gap-2">
                    <input type="checkbox" id="availableForIp" checked={formData.availableForIp} onChange={e => setFormData({...formData, availableForIp: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                    <label htmlFor="availableForIp" className="text-sm text-slate-700">Available for IP</label>
                  </div>
                  <div className="flex items-center gap-2">
                    <input type="checkbox" id="availableForEmergency" checked={formData.availableForEmergency} onChange={e => setFormData({...formData, availableForEmergency: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                    <label htmlFor="availableForEmergency" className="text-sm text-slate-700">Available for Emergency</label>
                  </div>
                </div>
              </section>

              {/* System */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">System</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Status <span className="text-red-500">*</span></label>
                    <select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Remarks</label>
                    <input type="text" maxLength={LIMITS.remarks} value={formData.remarks} onChange={e => setFormData({...formData, remarks: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                    <p className="text-slate-400 text-xs mt-1 text-right">{formData.remarks.length}/{LIMITS.remarks}</p>
                  </div>
                </div>
              </section>
            </div>

            <div className="p-4 border-t border-slate-100 bg-slate-50/50 flex justify-between items-center shrink-0">
              <Button variant="outline" color="secondary" onClick={() => setFormData(emptyData)} icon={RefreshCw}>
                Reset
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" color="secondary" onClick={() => { setIsFormOpen(false); setSelectedRecord(null); }}>
                  Cancel
                </Button>
                <Button variant="filled" color="primary" onClick={handleSaveForm} icon={Save} disabled={isSaving}>
                  {isSaving ? 'Saving...' : (selectedRecord ? 'Update' : 'Save')}
                </Button>
              </div>
            </div>
          </div>
        </>
      )}

      <Modal
        isOpen={isDeleteOpen}
        onClose={() => setIsDeleteOpen(false)}
        title="Confirm Deletion"
        maxWidth="sm"
      >
        <div className="p-1">
          <div className="flex items-center gap-4 mb-6 text-amber-600 bg-amber-50 p-4 rounded-xl">
            <AlertTriangle className="w-8 h-8 shrink-0" />
            <p className="text-sm font-medium">
              Are you sure you want to delete Service <strong>{selectedRecord?.serviceName}</strong>?
              This action cannot be undone.
            </p>
          </div>
          <div className="flex justify-end gap-3">
            <Button variant="outline" color="secondary" onClick={() => setIsDeleteOpen(false)}>
              Cancel
            </Button>
            <Button variant="filled" color="danger" onClick={confirmDelete}>
              Confirm Delete
            </Button>
          </div>
        </div>
      </Modal>
    </motion.div>
  );
};
