import { useState, useEffect, type KeyboardEvent } from 'react';
import {
  Plus, Search, Filter, Download, Edit2, Trash2, AlertTriangle,
  Save, RefreshCw, X
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '../../../components/ui/Button';
import { Modal } from '../../../components/ui/Modal';
import { exportToExcel } from '../../../utils/exportToExcel';

const API_BASE = import.meta.env.VITE_API_URL as string;

interface EquipmentRecord {
  id: number;
  equipmentCode: string;
  equipmentName: string;
  manufacturer: string;
  model: string;
  serialNumber: string;
  purchaseDate: string;
  warrantyExpiryDate: string;
  supplier: string;
  purchaseCost: string;
  calibrationSchedule: string;
  nextMaintenanceDate: string;
  maintenanceVendor: string;
  lastServiceDate: string;
  hospital: string;
  branch: string;
  department: string;
  roomNumber: string;
  status: string;
  remarks: string;
  createdBy?: string;
  createdDate?: string;
  updatedBy?: string;
  updatedDate?: string;
}

// EquipmentCode is auto-generated by the backend (EQP-001 format)
type EquipmentForm = Omit<EquipmentRecord, 'id' | 'equipmentCode' | 'createdBy' | 'createdDate' | 'updatedBy' | 'updatedDate'>;

const emptyData: EquipmentForm = {
  equipmentName: '',
  manufacturer: '',
  model: '',
  serialNumber: '',
  purchaseDate: '',
  warrantyExpiryDate: '',
  supplier: '',
  purchaseCost: '',
  calibrationSchedule: '',
  nextMaintenanceDate: '',
  maintenanceVendor: '',
  lastServiceDate: '',
  hospital: 'Main Hospital',
  branch: 'Central',
  department: 'Radiology',
  roomNumber: '',
  status: 'Active',
  remarks: ''
};

// Field limits (aligned with backend schema + DB column sizes)
const LIMITS = {
  equipmentName: 150,
  manufacturer: 100,
  model: 100,
  serialNumber: 100,
  supplier: 150,
  maintenanceVendor: 150,
  location: 100,   // hospital / branch / department
  roomNumber: 50,
  remarks: 500,
  costMax: 999999999999.99,
};

const calibrationSchedules = ['Monthly', 'Quarterly', 'Bi-Annual', 'Annual'];

// Block characters invalid inside a decimal <input type="number">.
const blockDecimalKeys = (e: KeyboardEvent<HTMLInputElement>) => {
  if (['e', 'E', '+', '-'].includes(e.key)) e.preventDefault();
};

// Map API response → EquipmentRecord
const mapApiToRecord = (item: Record<string, unknown>): EquipmentRecord => ({
  id:                  item.id                  as number,
  equipmentCode:       item.equipmentCode       as string,
  equipmentName:       item.equipmentName       as string,
  manufacturer:        item.manufacturer        as string,
  model:               item.model               as string,
  serialNumber:        item.serialNumber        as string,
  purchaseDate:        (item.purchaseDate       as string) ?? '',
  warrantyExpiryDate:  (item.warrantyExpiryDate as string) ?? '',
  supplier:            (item.supplier           as string) ?? '',
  purchaseCost:        item.purchaseCost != null ? String(item.purchaseCost) : '',
  calibrationSchedule: item.calibrationSchedule as string,
  nextMaintenanceDate: (item.nextMaintenanceDate as string) ?? '',
  maintenanceVendor:   (item.maintenanceVendor  as string) ?? '',
  lastServiceDate:     (item.lastServiceDate    as string) ?? '',
  hospital:            item.hospital            as string,
  branch:              item.branch              as string,
  department:          item.department          as string,
  roomNumber:          (item.roomNumber         as string) ?? '',
  status:              item.status              as string,
  remarks:             (item.remarks            as string) ?? '',
  createdBy:           (item.createdBy          as string) ?? undefined,
  createdDate:         item.createdDate ? String(item.createdDate).split('T')[0] : undefined,
  updatedBy:           (item.updatedBy          as string) ?? undefined,
  updatedDate:         item.updatedDate ? String(item.updatedDate).split('T')[0] : undefined,
});

export const EquipmentMaster = () => {
  const [records, setRecords] = useState<EquipmentRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [nextCode, setNextCode] = useState('');

  // Filter States
  const [showFilters, setShowFilters] = useState(false);
  const [filterManufacturer, setFilterManufacturer] = useState('');
  const [filterStatus, setFilterStatus] = useState('');

  // Form States
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState<EquipmentRecord | null>(null);
  const [formData, setFormData] = useState<EquipmentForm>(emptyData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const today = new Date().toISOString().split('T')[0];

  // ── Fetch equipment ──────────────────────────────────────────
  const fetchEquipment = async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/equipment/`);
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data: Record<string, unknown>[] = await res.json();
      setRecords(data.map(mapApiToRecord));
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Failed to load equipment');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchEquipment(); }, []);

  const fetchNextCode = async () => {
    setNextCode('');
    try {
      const res = await fetch(`${API_BASE}/equipment/next-code`);
      if (res.ok) {
        const data = await res.json();
        setNextCode(data.equipmentCode ?? '');
      }
    } catch {
      setNextCode('');
    }
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.equipmentName.trim()) newErrors.equipmentName = 'Equipment Name is required';
    if (!formData.manufacturer.trim()) newErrors.manufacturer = 'Manufacturer is required';
    if (!formData.model.trim()) newErrors.model = 'Model is required';
    if (!formData.serialNumber.trim()) newErrors.serialNumber = 'Serial Number is required';
    if (!formData.calibrationSchedule) newErrors.calibrationSchedule = 'Calibration Schedule is required';
    if (!formData.hospital.trim()) newErrors.hospital = 'Hospital is required';
    if (!formData.branch.trim()) newErrors.branch = 'Branch is required';
    if (!formData.department.trim()) newErrors.department = 'Department is required';

    if (formData.purchaseCost.trim() && Number(formData.purchaseCost) < 0)
      newErrors.purchaseCost = 'Purchase Cost cannot be negative';
    else if (formData.purchaseCost.trim() && Number(formData.purchaseCost) > LIMITS.costMax)
      newErrors.purchaseCost = 'Purchase Cost is too large';

    // ── Date rules (mirror the backend) ──────────────────────
    if (!formData.purchaseDate) newErrors.purchaseDate = 'Purchase Date is required';
    if (!formData.nextMaintenanceDate) newErrors.nextMaintenanceDate = 'Next Maintenance Date is required';

    if (formData.purchaseDate) {
      if (formData.purchaseDate > today) newErrors.purchaseDate = 'Purchase Date cannot be in the future';

      if (formData.nextMaintenanceDate && formData.nextMaintenanceDate <= formData.purchaseDate)
        newErrors.nextMaintenanceDate = 'Next Maintenance Date must be after Purchase Date';

      if (formData.warrantyExpiryDate && formData.warrantyExpiryDate < formData.purchaseDate)
        newErrors.warrantyExpiryDate = 'Warranty Expiry cannot be before Purchase Date';

      if (formData.lastServiceDate) {
        if (formData.lastServiceDate < formData.purchaseDate)
          newErrors.lastServiceDate = 'Last Service cannot be before Purchase Date';
        else if (formData.lastServiceDate > today)
          newErrors.lastServiceDate = 'Last Service cannot be in the future';
      }
    }

    // Serial uniqueness (Equipment Code is auto-generated)
    if (records.some(r => r.serialNumber.toLowerCase() === formData.serialNumber.trim().toLowerCase() && r.id !== selectedRecord?.id))
      newErrors.serialNumber = 'Serial Number must be unique';

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleCreateNew = () => {
    setSelectedRecord(null);
    setFormData(emptyData);
    setErrors({});
    setIsFormOpen(true);
    fetchNextCode();
  };

  const handleEdit = (record: EquipmentRecord) => {
    setSelectedRecord(record);
    const { id, equipmentCode, createdBy, createdDate, updatedBy, updatedDate, ...rest } = record;
    setFormData(rest);
    setErrors({});
    setIsFormOpen(true);
  };

  const handleDeleteRequest = (record: EquipmentRecord) => {
    setSelectedRecord(record);
    setIsDeleteOpen(true);
  };

  const handleSaveForm = async () => {
    if (!validateForm()) return;
    setIsSaving(true);
    setApiError(null);
    try {
      const body = {
        equipmentName:       formData.equipmentName.trim(),
        manufacturer:        formData.manufacturer.trim(),
        model:               formData.model.trim(),
        serialNumber:        formData.serialNumber.trim(),
        purchaseDate:        formData.purchaseDate,
        warrantyExpiryDate:  formData.warrantyExpiryDate || null,
        supplier:            formData.supplier || null,
        purchaseCost:        formData.purchaseCost === '' ? null : Number(formData.purchaseCost),
        calibrationSchedule: formData.calibrationSchedule,
        nextMaintenanceDate: formData.nextMaintenanceDate,
        maintenanceVendor:   formData.maintenanceVendor || null,
        lastServiceDate:     formData.lastServiceDate || null,
        hospital:            formData.hospital.trim(),
        branch:              formData.branch.trim(),
        department:          formData.department.trim(),
        roomNumber:          formData.roomNumber || null,
        status:              formData.status,
        remarks:             formData.remarks || null,
      };

      let res: Response;
      if (selectedRecord) {
        res = await fetch(`${API_BASE}/equipment/${selectedRecord.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, updatedBy: 'Admin' }),
        });
      } else {
        res = await fetch(`${API_BASE}/equipment/`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, createdBy: 'Admin' }),
        });
      }
      if (!res.ok) {
        const data = await res.json().catch(() => null);
        const detail = data && typeof data.detail === 'string' ? data.detail : `Save failed: ${res.status}`;
        throw new Error(detail);
      }

      await fetchEquipment();
      setIsFormOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setIsSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!selectedRecord) return;
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/equipment/${selectedRecord.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`Delete failed: ${res.status}`);
      await fetchEquipment();
      setIsDeleteOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Delete failed');
      setIsDeleteOpen(false);
    }
  };

  const manufacturers = Array.from(new Set(records.map(r => r.manufacturer)));

  const filteredRecords = records.filter(record => {
    const matchesSearch =
      record.equipmentName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.equipmentCode.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.model.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesManufacturer = !filterManufacturer || record.manufacturer === filterManufacturer;
    const matchesStatus = !filterStatus || record.status === filterStatus;

    return matchesSearch && matchesManufacturer && matchesStatus;
  });

  const _totalPages = Math.max(1, Math.ceil(filteredRecords.length / itemsPerPage));
  const _page = Math.min(currentPage, _totalPages);
  const pagedRecords = filteredRecords.slice((_page - 1) * itemsPerPage, _page * itemsPerPage);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="h-full flex flex-col relative"
    >
      {apiError && (
        <div className="mb-4 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span className="flex-1">{apiError}</span>
          <button onClick={() => setApiError(null)} className="text-red-500 hover:text-red-700 font-medium">Dismiss</button>
        </div>
      )}

      {!isFormOpen ? (
        <>
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-slate-800">Equipment Master</h1>
              <p className="text-slate-500 mt-1"></p>
            </div>
            <div className="flex gap-3">
              <Button variant="filled" color="primary" icon={Plus} onClick={handleCreateNew}>
                Add Equipment
              </Button>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex flex-wrap gap-4 items-center justify-between">
              <div className="relative flex-1 max-w-md">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search by Machine Name, Code or Model..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary text-sm"
                />
              </div>
              <div className="flex items-center gap-2">
              <button onClick={() => setShowFilters(!showFilters)} title="Filters" className={showFilters ? "p-2 border rounded-lg transition-colors border-primary bg-primary/5 text-primary" : "p-2 border rounded-lg transition-colors border-slate-200 text-slate-500 hover:bg-slate-50"}>
                <Filter className="w-4 h-4" />
              </button>
              <button onClick={() => { setSearchTerm(''); setFilterManufacturer(''); setFilterStatus(''); }} title="Clear search & filters" className="p-2 border border-red-200 rounded-lg text-red-500 hover:bg-red-50 hover:border-red-300 transition-colors">
                <X className="w-4 h-4" />
              </button>
              <button onClick={() => exportToExcel(records, 'EquipmentMaster')} title="Export to Excel" className="p-2 border border-emerald-200 rounded-lg text-emerald-600 hover:bg-emerald-50 hover:border-emerald-300 transition-colors">
                <Download className="w-4 h-4" />
              </button>
            </div>
            </div>

            <AnimatePresence>
              {showFilters && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="border-b border-slate-200 bg-slate-50/50 p-4"
                >
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <select
                      value={filterManufacturer}
                      onChange={(e) => setFilterManufacturer(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Manufacturers</option>
                      {manufacturers.map(m => <option key={m} value={m}>{m}</option>)}
                    </select>
                    <select
                      value={filterStatus}
                      onChange={(e) => setFilterStatus(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Statuses</option>
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="flex-1 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600">
                  <tr>
                    <th className="px-4 py-3 font-medium">Equipment Code</th>
                    <th className="px-4 py-3 font-medium">Machine Name</th>
                    <th className="px-4 py-3 font-medium">Manufacturer</th>
                    <th className="px-4 py-3 font-medium">Model</th>
                    <th className="px-4 py-3 font-medium text-center">Next Maintenance</th>
                    <th className="px-4 py-3 font-medium text-center">Status</th>
                    <th className="px-4 py-3 font-medium text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {isLoading ? (
                    <tr>
                      <td colSpan={7} className="px-4 py-8 text-center text-slate-500">
                        Loading equipment...
                      </td>
                    </tr>
                  ) : filteredRecords.length > 0 ? (
                    pagedRecords.map((record) => (
                      <tr key={record.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-3 font-medium text-slate-800">{record.equipmentCode}</td>
                        <td className="px-4 py-3">{record.equipmentName}</td>
                        <td className="px-4 py-3 text-slate-600">{record.manufacturer}</td>
                        <td className="px-4 py-3 text-slate-600">{record.model}</td>
                        <td className="px-4 py-3 text-center text-slate-600">{record.nextMaintenanceDate}</td>
                        <td className="px-4 py-3 text-center">
                          <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${
                            record.status === 'Active'
                              ? 'bg-emerald-50 text-emerald-600 border border-emerald-200'
                              : 'bg-red-50 text-red-600 border border-red-200'
                          }`}>
                            {record.status}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => handleEdit(record)}
                              className="p-1.5 text-slate-400 hover:text-primary hover:bg-primary/5 rounded-lg transition-colors"
                              title="Edit"
                            >
                              <Edit2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteRequest(record)}
                              className="p-1.5 text-red-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={7} className="px-4 py-8 text-center text-slate-500">
                        No equipment records found matching your criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            <div className="flex flex-wrap items-center justify-between gap-3 p-4 border-t border-slate-100 text-sm text-slate-500">
              <div className="flex items-center gap-2">
                <span>Show</span>
                <select value={itemsPerPage} onChange={(e) => { setItemsPerPage(Number(e.target.value)); setCurrentPage(1); }} className="px-2 py-1 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                  <option value={10}>10</option>
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>
                <span>entries</span>
                <span className="text-slate-400">· {filteredRecords.length} total</span>
              </div>
              <div className="flex items-center gap-3">
                <span>Page {_page} of {_totalPages}</span>
                <div className="flex gap-1">
                  <button onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={_page <= 1} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Prev</button>
                  <button onClick={() => setCurrentPage(p => Math.min(_totalPages, p + 1))} disabled={_page >= _totalPages} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Next</button>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : (
        <>
          <div className="flex justify-between items-center mb-6">
            <div>
              <h1 className="text-2xl font-bold text-slate-800">
                {selectedRecord ? `Edit Equipment: ${selectedRecord.equipmentName}` : 'Add New Equipment'}
              </h1>
              <p className="text-slate-500 text-sm">Register a radiology machine</p>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="flex-1 overflow-y-auto p-5 space-y-4">
              {/* Basic Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Basic Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Equipment Code</label>
                    <input type="text" value={selectedRecord ? selectedRecord.equipmentCode : (nextCode || 'Auto-generating…')} disabled readOnly className="w-full px-4 py-2 bg-slate-100 border border-slate-200 rounded-xl text-sm text-slate-500 cursor-not-allowed" />
                    {!selectedRecord && nextCode && (
                      <p className="text-slate-400 text-xs mt-1">Provisional — final code is assigned on save</p>
                    )}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Equipment Name <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.equipmentName} value={formData.equipmentName} onChange={e => setFormData({...formData, equipmentName: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.equipmentName ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.equipmentName && <p className="text-red-500 text-xs mt-1">{errors.equipmentName}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Manufacturer <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.manufacturer} value={formData.manufacturer} onChange={e => setFormData({...formData, manufacturer: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.manufacturer ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.manufacturer && <p className="text-red-500 text-xs mt-1">{errors.manufacturer}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Model <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.model} value={formData.model} onChange={e => setFormData({...formData, model: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.model ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.model && <p className="text-red-500 text-xs mt-1">{errors.model}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Serial Number <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.serialNumber} value={formData.serialNumber} onChange={e => setFormData({...formData, serialNumber: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.serialNumber ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.serialNumber && <p className="text-red-500 text-xs mt-1">{errors.serialNumber}</p>}
                  </div>
                </div>
              </section>

              {/* Purchase Details */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Purchase Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Purchase Date <span className="text-red-500">*</span></label>
                    <input type="date" max={today} value={formData.purchaseDate} onChange={e => setFormData({...formData, purchaseDate: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.purchaseDate ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.purchaseDate && <p className="text-red-500 text-xs mt-1">{errors.purchaseDate}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Warranty Expiry Date (Optional)</label>
                    <input type="date" min={formData.purchaseDate || undefined} value={formData.warrantyExpiryDate} onChange={e => setFormData({...formData, warrantyExpiryDate: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.warrantyExpiryDate ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.warrantyExpiryDate && <p className="text-red-500 text-xs mt-1">{errors.warrantyExpiryDate}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Supplier (Optional)</label>
                    <input type="text" maxLength={LIMITS.supplier} value={formData.supplier} onChange={e => setFormData({...formData, supplier: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Purchase Cost (Optional)</label>
                    <input type="number" min="0" step="0.01" onKeyDown={blockDecimalKeys} value={formData.purchaseCost} onChange={e => setFormData({...formData, purchaseCost: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.purchaseCost ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.purchaseCost && <p className="text-red-500 text-xs mt-1">{errors.purchaseCost}</p>}
                  </div>
                </div>
              </section>

              {/* Maintenance Details */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Maintenance Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Calibration Schedule <span className="text-red-500">*</span></label>
                    <select value={formData.calibrationSchedule} onChange={e => setFormData({...formData, calibrationSchedule: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.calibrationSchedule ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`}>
                      <option value="">Select Schedule</option>
                      {calibrationSchedules.map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                    {errors.calibrationSchedule && <p className="text-red-500 text-xs mt-1">{errors.calibrationSchedule}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Next Maintenance Date <span className="text-red-500">*</span></label>
                    <input type="date" min={formData.purchaseDate || undefined} value={formData.nextMaintenanceDate} onChange={e => setFormData({...formData, nextMaintenanceDate: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.nextMaintenanceDate ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.nextMaintenanceDate && <p className="text-red-500 text-xs mt-1">{errors.nextMaintenanceDate}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Maintenance Vendor (Optional)</label>
                    <input type="text" maxLength={LIMITS.maintenanceVendor} value={formData.maintenanceVendor} onChange={e => setFormData({...formData, maintenanceVendor: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Last Service Date (Optional)</label>
                    <input type="date" min={formData.purchaseDate || undefined} max={today} value={formData.lastServiceDate} onChange={e => setFormData({...formData, lastServiceDate: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.lastServiceDate ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.lastServiceDate && <p className="text-red-500 text-xs mt-1">{errors.lastServiceDate}</p>}
                  </div>
                </div>
              </section>

              {/* Location Details */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Location Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Hospital <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.location} value={formData.hospital} onChange={e => setFormData({...formData, hospital: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.hospital ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.hospital && <p className="text-red-500 text-xs mt-1">{errors.hospital}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Branch <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.location} value={formData.branch} onChange={e => setFormData({...formData, branch: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.branch ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.branch && <p className="text-red-500 text-xs mt-1">{errors.branch}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Department <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.location} value={formData.department} onChange={e => setFormData({...formData, department: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.department ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.department && <p className="text-red-500 text-xs mt-1">{errors.department}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Room Number (Optional)</label>
                    <input type="text" maxLength={LIMITS.roomNumber} value={formData.roomNumber} onChange={e => setFormData({...formData, roomNumber: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

              {/* System Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">System Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Status <span className="text-red-500">*</span></label>
                    <select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Remarks (Optional)</label>
                    <input type="text" maxLength={LIMITS.remarks} value={formData.remarks} onChange={e => setFormData({...formData, remarks: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                    <p className="text-slate-400 text-xs mt-1 text-right">{formData.remarks.length}/{LIMITS.remarks}</p>
                  </div>
                </div>
              </section>
            </div>

            <div className="p-4 border-t border-slate-100 bg-slate-50/50 flex justify-between items-center shrink-0">
              <Button variant="outline" color="secondary" onClick={() => setFormData(emptyData)} icon={RefreshCw}>
                Reset
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" color="secondary" onClick={() => { setIsFormOpen(false); setSelectedRecord(null); }}>
                  Cancel
                </Button>
                <Button variant="filled" color="primary" onClick={handleSaveForm} icon={Save} disabled={isSaving}>
                  {isSaving ? 'Saving...' : (selectedRecord ? 'Update' : 'Save')}
                </Button>
              </div>
            </div>
          </div>
        </>
      )}

      <Modal
        isOpen={isDeleteOpen}
        onClose={() => setIsDeleteOpen(false)}
        title="Confirm Deletion"
        maxWidth="sm"
      >
        <div className="p-1">
          <div className="flex items-center gap-4 mb-6 text-amber-600 bg-amber-50 p-4 rounded-xl">
            <AlertTriangle className="w-8 h-8 shrink-0" />
            <p className="text-sm font-medium">
              Are you sure you want to delete Equipment <strong>{selectedRecord?.equipmentName}</strong>?
              This action cannot be undone.
            </p>
          </div>
          <div className="flex justify-end gap-3">
            <Button variant="outline" color="secondary" onClick={() => setIsDeleteOpen(false)}>
              Cancel
            </Button>
            <Button variant="filled" color="danger" onClick={confirmDelete}>
              Confirm Delete
            </Button>
          </div>
        </div>
      </Modal>
    </motion.div>
  );
};
