import { useState, useEffect, type KeyboardEvent } from 'react';
import {
  Plus, Search, Filter, Download, Edit2, Trash2, AlertTriangle,
  Save, RefreshCw, X
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '../../../components/ui/Button';
import { Modal } from '../../../components/ui/Modal';
import { exportToExcel } from '../../../utils/exportToExcel';

const API_BASE = import.meta.env.VITE_API_URL as string;

interface RadiologyServiceRecord {
  id: number;
  serviceCode: string;
  serviceName: string;
  description: string;
  serviceCategory: string;
  estimatedDuration: string;
  reportTat: string;
  requiresAppointment: boolean;
  requiresContrast: boolean;
  requiresFasting: boolean;
  servicePrice: string;
  gst: string;
  reportTemplate: string;
  requiresApproval: boolean;
  criticalFindingAlert: boolean;
  status: string;
  remarks: string;
  createdBy?: string;
  createdDate?: string;
  updatedBy?: string;
  updatedDate?: string;
}

// ServiceCode is auto-generated by the backend (RAD-001 format)
type RadiologyServiceForm = Omit<RadiologyServiceRecord, 'id' | 'serviceCode' | 'createdBy' | 'createdDate' | 'updatedBy' | 'updatedDate'>;

const emptyData: RadiologyServiceForm = {
  serviceName: '',
  description: '',
  serviceCategory: '',
  estimatedDuration: '',
  reportTat: '',
  requiresAppointment: true,
  requiresContrast: false,
  requiresFasting: false,
  servicePrice: '',
  gst: '',
  reportTemplate: '',
  requiresApproval: true,
  criticalFindingAlert: false,
  status: 'Active',
  remarks: ''
};

// Map API response → RadiologyServiceRecord
const mapApiToRecord = (item: Record<string, unknown>): RadiologyServiceRecord => ({
  id:                   item.id                   as number,
  serviceCode:          item.serviceCode          as string,
  serviceName:          item.serviceName          as string,
  description:          (item.description         as string) ?? '',
  serviceCategory:      item.serviceCategory      as string,
  estimatedDuration:    String(item.estimatedDuration ?? ''),
  reportTat:            String(item.reportTat ?? ''),
  requiresAppointment:  Boolean(item.requiresAppointment),
  requiresContrast:     Boolean(item.requiresContrast),
  requiresFasting:      Boolean(item.requiresFasting),
  servicePrice:         String(item.servicePrice ?? ''),
  gst:                  item.gst != null ? String(item.gst) : '',
  reportTemplate:       (item.reportTemplate      as string) ?? '',
  requiresApproval:     Boolean(item.requiresApproval),
  criticalFindingAlert: Boolean(item.criticalFindingAlert),
  status:               item.status               as string,
  remarks:              (item.remarks             as string) ?? '',
  createdBy:            (item.createdBy           as string) ?? undefined,
  createdDate:          item.createdDate ? String(item.createdDate).split('T')[0] : undefined,
  updatedBy:            (item.updatedBy           as string) ?? undefined,
  updatedDate:          item.updatedDate ? String(item.updatedDate).split('T')[0] : undefined,
});

const serviceCategories = ['X-Ray', 'CT Scan', 'MRI', 'Ultrasound', 'Mammogram', 'ECG', 'Echo', 'PET Scan'];
// Field limits (aligned with DB column sizes / sensible ranges)
const LIMITS = {
  serviceName: 150,     // DB VARCHAR(255)
  description: 500,     // DB VARCHAR(500)
  reportTemplate: 255,  // DB VARCHAR(255)
  remarks: 500,         // DB TEXT (capped for UI)
  durationMax: 1440,    // minutes (24 h)
  tatMax: 720,          // hours (30 days)
  priceMax: 9999999,    // DECIMAL(12,2)
};

// Block characters that are invalid inside numeric <input type="number">.
const blockIntKeys = (e: KeyboardEvent<HTMLInputElement>) => {
  if (['e', 'E', '+', '-', '.'].includes(e.key)) e.preventDefault();
};
const blockDecimalKeys = (e: KeyboardEvent<HTMLInputElement>) => {
  if (['e', 'E', '+', '-'].includes(e.key)) e.preventDefault();
};

export const RadiologyServiceMaster = () => {
  const [records, setRecords] = useState<RadiologyServiceRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [nextCode, setNextCode] = useState('');   // provisional auto-code preview

  // Filter States
  const [showFilters, setShowFilters] = useState(false);
  const [filterCategory, setFilterCategory] = useState('');

  // Form States
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState<RadiologyServiceRecord | null>(null);
  const [formData, setFormData] = useState<RadiologyServiceForm>(emptyData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // ── Fetch radiology services ─────────────────────────────────
  const fetchRadiologyServices = async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/radiology-services/`);
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data: Record<string, unknown>[] = await res.json();
      setRecords(data.map(mapApiToRecord));
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Failed to load radiology services');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { 
    fetchRadiologyServices(); 
  }, []);

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.serviceName.trim()) newErrors.serviceName = 'Service Name is required';
    if (!formData.serviceCategory) newErrors.serviceCategory = 'Service Category is required';

    if (!formData.estimatedDuration.trim()) newErrors.estimatedDuration = 'Estimated Duration is required';
    else if (Number(formData.estimatedDuration) <= 0) newErrors.estimatedDuration = 'Duration must be greater than zero';
    else if (!Number.isInteger(Number(formData.estimatedDuration))) newErrors.estimatedDuration = 'Duration must be a whole number of minutes';
    else if (Number(formData.estimatedDuration) > LIMITS.durationMax) newErrors.estimatedDuration = `Duration cannot exceed ${LIMITS.durationMax} minutes`;

    if (!formData.reportTat.trim()) newErrors.reportTat = 'Report Turnaround Time is required';
    else if (Number(formData.reportTat) <= 0) newErrors.reportTat = 'Turnaround Time must be greater than zero';
    else if (!Number.isInteger(Number(formData.reportTat))) newErrors.reportTat = 'Turnaround Time must be a whole number of hours';
    else if (Number(formData.reportTat) > LIMITS.tatMax) newErrors.reportTat = `Turnaround Time cannot exceed ${LIMITS.tatMax} hours`;

    if (!formData.servicePrice.trim()) newErrors.servicePrice = 'Service Price is required';
    else if (Number(formData.servicePrice) <= 0) newErrors.servicePrice = 'Price must be greater than zero';
    else if (Number(formData.servicePrice) > LIMITS.priceMax) newErrors.servicePrice = `Price cannot exceed ${LIMITS.priceMax.toLocaleString()}`;

    // Uniqueness check (Service Code is auto-generated, so only name is checked)
    if (records.some(r => r.serviceName.toLowerCase() === formData.serviceName.trim().toLowerCase() && r.id !== selectedRecord?.id)) {
      newErrors.serviceName = 'Service Name must be unique';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Fetch the provisional next Service Code from the backend (uses the same
  // DB logic as insert, so it stays correct even with soft-deleted rows).
  const fetchNextCode = async () => {
    setNextCode('');
    try {
      const res = await fetch(`${API_BASE}/radiology-services/next-code`);
      if (res.ok) {
        const data = await res.json();
        setNextCode(data.serviceCode ?? '');
      }
    } catch {
      setNextCode('');   // fall back to placeholder text
    }
  };

  const handleCreateNew = () => {
    setSelectedRecord(null);
    setFormData(emptyData);
    setErrors({});
    setIsFormOpen(true);
    fetchNextCode();
  };

  const handleEdit = (record: RadiologyServiceRecord) => {
    setSelectedRecord(record);
    const { id, serviceCode, createdBy, createdDate, updatedBy, updatedDate, ...rest } = record;
    setFormData(rest);
    setErrors({});
    setIsFormOpen(true);
  };

  const handleDeleteRequest = (record: RadiologyServiceRecord) => {
    setSelectedRecord(record);
    setIsDeleteOpen(true);
  };

  const handleSaveForm = async () => {
    if (!validateForm()) return;
    setIsSaving(true);
    setApiError(null);
    try {
      const body = {
        serviceName:          formData.serviceName.trim(),
        description:          formData.description || null,
        serviceCategory:      formData.serviceCategory,
        estimatedDuration:    Number(formData.estimatedDuration),
        reportTat:            Number(formData.reportTat),
        requiresAppointment:  formData.requiresAppointment,
        requiresContrast:     formData.requiresContrast,
        requiresFasting:      formData.requiresFasting,
        servicePrice:         Number(formData.servicePrice),
        gst:                  formData.gst === '' ? null : Number(formData.gst),
        reportTemplate:       formData.reportTemplate || null,
        requiresApproval:     formData.requiresApproval,
        criticalFindingAlert: formData.criticalFindingAlert,
        status:               formData.status,
        remarks:              formData.remarks || null,
      };

      if (selectedRecord) {
        const res = await fetch(`${API_BASE}/radiology-services/${selectedRecord.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, updatedBy: 'Admin' }),
        });
        if (!res.ok) throw new Error(`Update failed: ${res.status}`);
      } else {
        const res = await fetch(`${API_BASE}/radiology-services/`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, createdBy: 'Admin' }),
        });
        if (!res.ok) throw new Error(`Create failed: ${res.status}`);
      }

      await fetchRadiologyServices();
      setIsFormOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setIsSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!selectedRecord) return;
    setApiError(null);
    try {
      // Soft Delete
      const res = await fetch(`${API_BASE}/radiology-services/${selectedRecord.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`Delete failed: ${res.status}`);
      await fetchRadiologyServices();
      setIsDeleteOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Delete failed');
      setIsDeleteOpen(false);
    }
  };

  const filteredRecords = records.filter(record => {
    const matchesSearch =
      record.serviceName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.serviceCode.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = !filterCategory || record.serviceCategory === filterCategory;

    return matchesSearch && matchesCategory;
  });

  const _totalPages = Math.max(1, Math.ceil(filteredRecords.length / itemsPerPage));
  const _page = Math.min(currentPage, _totalPages);
  const pagedRecords = filteredRecords.slice((_page - 1) * itemsPerPage, _page * itemsPerPage);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="h-full flex flex-col relative"
    >
      {apiError && (
        <div className="mb-4 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span className="flex-1">{apiError}</span>
          <button onClick={() => setApiError(null)} className="text-red-500 hover:text-red-700 font-medium">Dismiss</button>
        </div>
      )}

      {!isFormOpen ? (
        <>
          <div className="flex items-center justify-between mb-4">
            <div>
              <h1 className="text-3xl font-bold text-slate-800">Radiology Service</h1>
              <p className="text-slate-500 mt-1"></p>
            </div>
            <div className="flex gap-3">
              <Button variant="filled" color="primary" icon={Plus} onClick={handleCreateNew}>
                Add Service
              </Button>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex flex-wrap gap-4 items-center justify-between">
              <div className="relative flex-1 max-w-md">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search by Service Name or Code..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary text-sm"
                />
              </div>
              <div className="flex items-center gap-2">
              <button onClick={() => setShowFilters(!showFilters)} title="Filters" className={showFilters ? "p-2 border rounded-lg transition-colors border-primary bg-primary/5 text-primary" : "p-2 border rounded-lg transition-colors border-slate-200 text-slate-500 hover:bg-slate-50"}>
                <Filter className="w-4 h-4" />
              </button>
              <button onClick={() => { setSearchTerm(''); setFilterCategory(''); }} title="Clear search & filters" className="p-2 border border-red-200 rounded-lg text-red-500 hover:bg-red-50 hover:border-red-300 transition-colors">
                <X className="w-4 h-4" />
              </button>
              <button onClick={() => exportToExcel(records, 'RadiologyServiceMaster')} title="Export to Excel" className="p-2 border border-emerald-200 rounded-lg text-emerald-600 hover:bg-emerald-50 hover:border-emerald-300 transition-colors">
                <Download className="w-4 h-4" />
              </button>
            </div>
            </div>

            <AnimatePresence>
              {showFilters && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="border-b border-slate-200 bg-slate-50/50 p-4"
                >
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <select
                      value={filterCategory}
                      onChange={(e) => setFilterCategory(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Categories</option>
                      {serviceCategories.map(sc => <option key={sc} value={sc}>{sc}</option>)}
                    </select>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="flex-1 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600">
                  <tr>
                    <th className="px-4 py-3 font-medium">Service Code</th>
                    <th className="px-4 py-3 font-medium">Service Name</th>
                    <th className="px-4 py-3 font-medium text-right">Price (₹)</th>
                    <th className="px-4 py-3 font-medium text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {isLoading ? (
                    <tr>
                      <td colSpan={5} className="px-4 py-8 text-center text-slate-500">
                        Loading radiology services...
                      </td>
                    </tr>
                  ) : filteredRecords.length > 0 ? (
                    pagedRecords.map((record) => (
                      <tr key={record.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-3 font-medium text-slate-800">{record.serviceCode}</td>
                        <td className="px-4 py-3">
                          {record.serviceName}
                          {record.requiresContrast && <span className="ml-2 px-1.5 py-0.5 bg-purple-100 text-purple-700 rounded text-[10px] font-bold" title="Contrast Required">CON</span>}
                        </td>
                        <td className="px-4 py-3 text-right font-medium text-slate-700">{record.servicePrice}</td>
                        <td className="px-4 py-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => handleEdit(record)}
                              className="p-1.5 text-slate-400 hover:text-primary hover:bg-primary/5 rounded-lg transition-colors"
                              title="Edit"
                            >
                              <Edit2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteRequest(record)}
                              className="p-1.5 text-red-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={5} className="px-4 py-8 text-center text-slate-500">
                        No radiology services found matching your criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            <div className="flex flex-wrap items-center justify-between gap-3 p-4 border-t border-slate-100 text-sm text-slate-500">
              <div className="flex items-center gap-2">
                <span>Show</span>
                <select value={itemsPerPage} onChange={(e) => { setItemsPerPage(Number(e.target.value)); setCurrentPage(1); }} className="px-2 py-1 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                  <option value={10}>10</option>
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>
                <span>entries</span>
                <span className="text-slate-400">· {filteredRecords.length} total</span>
              </div>
              <div className="flex items-center gap-3">
                <span>Page {_page} of {_totalPages}</span>
                <div className="flex gap-1">
                  <button onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={_page <= 1} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Prev</button>
                  <button onClick={() => setCurrentPage(p => Math.min(_totalPages, p + 1))} disabled={_page >= _totalPages} className="px-3 py-1 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed">Next</button>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : (
        <>
          <div className="flex justify-between items-center mb-2">
            <div>
              <h1 className="text-2xl font-bold text-slate-800">
                {selectedRecord ? `Edit Service: ${selectedRecord.serviceName}` : 'Add New Service'}
              </h1>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="flex-1 overflow-y-auto p-5 space-y-4">
              {/* Basic Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Basic Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Service Code</label>
                    <input type="text" value={selectedRecord ? selectedRecord.serviceCode : (nextCode || 'Auto-generating…')} disabled readOnly className="w-full px-4 py-2 bg-slate-100 border border-slate-200 rounded-xl text-sm text-slate-500 cursor-not-allowed" />
                    {!selectedRecord && nextCode && (
                      <p className="text-slate-400 text-xs mt-1">Provisional — final code is assigned on save</p>
                    )}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Service Name <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.serviceName} value={formData.serviceName} onChange={e => setFormData({...formData, serviceName: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.serviceName ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.serviceName && <p className="text-red-500 text-xs mt-1">{errors.serviceName}</p>}
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Description (Optional)</label>
                    <input type="text" maxLength={LIMITS.description} value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

              {/* Service Details */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Service Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Service Category <span className="text-red-500">*</span></label>
                    <select value={formData.serviceCategory} onChange={e => setFormData({...formData, serviceCategory: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.serviceCategory ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`}>
                      <option value="">Select Category</option>
                      {serviceCategories.map(c => <option key={c} value={c}>{c}</option>)}
                    </select>
                    {errors.serviceCategory && <p className="text-red-500 text-xs mt-1">{errors.serviceCategory}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Estimated Duration (Mins) <span className="text-red-500">*</span></label>
                    <input type="number" min="1" max={LIMITS.durationMax} step="1" onKeyDown={blockIntKeys} value={formData.estimatedDuration} onChange={e => setFormData({...formData, estimatedDuration: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.estimatedDuration ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.estimatedDuration && <p className="text-red-500 text-xs mt-1">{errors.estimatedDuration}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Report Turnaround Time (Hrs) <span className="text-red-500">*</span></label>
                    <input type="number" min="1" max={LIMITS.tatMax} step="1" onKeyDown={blockIntKeys} value={formData.reportTat} onChange={e => setFormData({...formData, reportTat: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.reportTat ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.reportTat && <p className="text-red-500 text-xs mt-1">{errors.reportTat}</p>}
                  </div>
                  <div className="lg:col-span-3 flex flex-wrap gap-4 mt-2">
                    <div className="flex items-center gap-2">
                      <input type="checkbox" id="requiresAppointment" checked={formData.requiresAppointment} onChange={e => setFormData({...formData, requiresAppointment: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                      <label htmlFor="requiresAppointment" className="text-sm text-slate-700 font-medium">Requires Appointment</label>
                    </div>
                    <div className="flex items-center gap-2">
                      <input type="checkbox" id="requiresContrast" checked={formData.requiresContrast} onChange={e => setFormData({...formData, requiresContrast: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                      <label htmlFor="requiresContrast" className="text-sm text-slate-700 font-medium">Requires Contrast</label>
                    </div>
                    <div className="flex items-center gap-2">
                      <input type="checkbox" id="requiresFasting" checked={formData.requiresFasting} onChange={e => setFormData({...formData, requiresFasting: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                      <label htmlFor="requiresFasting" className="text-sm text-slate-700 font-medium">Requires Fasting</label>
                    </div>
                  </div>
                </div>
              </section>

              {/* Billing Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Billing Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Service Price (₹) <span className="text-red-500">*</span></label>
                    <input type="number" min="0" max={LIMITS.priceMax} step="0.01" onKeyDown={blockDecimalKeys} value={formData.servicePrice} onChange={e => setFormData({...formData, servicePrice: e.target.value})} className={`w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${errors.servicePrice ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`} />
                    {errors.servicePrice && <p className="text-red-500 text-xs mt-1">{errors.servicePrice}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">GST/Tax (%) (Optional)</label>
                    <input type="number" min="0" max="100" step="0.01" onKeyDown={blockDecimalKeys} value={formData.gst} onChange={e => setFormData({...formData, gst: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

              {/* Report Configuration */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Report Configuration</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Report Template (Optional)</label>
                    <input type="text" maxLength={LIMITS.reportTemplate} value={formData.reportTemplate} onChange={e => setFormData({...formData, reportTemplate: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                  <div className="flex flex-col gap-3 justify-center">
                    <div className="flex items-center gap-2">
                      <input type="checkbox" id="requiresApproval" checked={formData.requiresApproval} onChange={e => setFormData({...formData, requiresApproval: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                      <label htmlFor="requiresApproval" className="text-sm text-slate-700 font-medium">Doctor Approval Required</label>
                    </div>
                    <div className="flex items-center gap-2">
                      <input type="checkbox" id="criticalFindingAlert" checked={formData.criticalFindingAlert} onChange={e => setFormData({...formData, criticalFindingAlert: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                      <label htmlFor="criticalFindingAlert" className="text-sm text-amber-600 font-bold flex items-center gap-1">
                        Critical Finding Alert
                        <AlertTriangle className="w-4 h-4" />
                      </label>
                    </div>
                  </div>
                </div>
              </section>


            </div>

            <div className="p-4 border-t border-slate-100 bg-slate-50/50 flex justify-between items-center shrink-0">
              <Button variant="outline" color="secondary" onClick={() => setFormData(emptyData)} icon={RefreshCw}>
                Reset
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" color="secondary" onClick={() => { setIsFormOpen(false); setSelectedRecord(null); }}>
                  Cancel
                </Button>
                <Button variant="filled" color="primary" onClick={handleSaveForm} icon={Save} disabled={isSaving}>
                  {isSaving ? 'Saving...' : (selectedRecord ? 'Update' : 'Save')}
                </Button>
              </div>
            </div>
          </div>
        </>
      )}

      <Modal
        isOpen={isDeleteOpen}
        onClose={() => setIsDeleteOpen(false)}
        title="Confirm Deletion"
        maxWidth="sm"
      >
        <div className="p-1">
          <div className="flex items-center gap-4 mb-6 text-amber-600 bg-amber-50 p-4 rounded-xl">
            <AlertTriangle className="w-8 h-8 shrink-0" />
            <p className="text-sm font-medium">
              Are you sure you want to delete Radiology Service <strong>{selectedRecord?.serviceName}</strong>?
              This action cannot be undone.
            </p>
          </div>
          <div className="flex justify-end gap-3">
            <Button variant="outline" color="secondary" onClick={() => setIsDeleteOpen(false)}>
              Cancel
            </Button>
            <Button variant="filled" color="danger" onClick={confirmDelete}>
              Confirm Delete
            </Button>
          </div>
        </div>
      </Modal>
    </motion.div>
  );
};


