import { useState, useEffect, type KeyboardEvent } from 'react';
import {
  Plus, Search, Filter, Download, Edit2, Trash2, AlertTriangle,
  Save, RefreshCw
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '../../../components/ui/Button';
import { Modal } from '../../../components/ui/Modal';
import { exportToExcel } from '../../../utils/exportToExcel';

const API_BASE = import.meta.env.VITE_API_URL as string;

interface TpaRecord {
  id: number;
  tpaCode: string;
  tpaName: string;
  insuranceProvider: string;
  registrationNumber: string;
  description: string;
  contactPerson: string;
  phoneNumber: string;
  alternatePhone: string;
  email: string;
  website: string;
  addressLine1: string;
  addressLine2: string;
  country: string;
  state: string;
  city: string;
  postalCode: string;
  claimProcessingTime: number | string;
  cashlessApproval: boolean;
  onlineClaimPortal: string;
  status: string;
  remarks: string;
  createdBy?: string;
  createdDate?: string;
  updatedBy?: string;
  updatedDate?: string;
}

// TpaCode is auto-generated by the backend (TPA-001 format)
type TpaForm = Omit<TpaRecord, 'id' | 'tpaCode' | 'createdBy' | 'createdDate' | 'updatedBy' | 'updatedDate'>;

const emptyData: TpaForm = {
  tpaName: '',
  insuranceProvider: '',
  registrationNumber: '',
  description: '',
  contactPerson: '',
  phoneNumber: '',
  alternatePhone: '',
  email: '',
  website: '',
  addressLine1: '',
  addressLine2: '',
  country: 'India',
  state: '',
  city: '',
  postalCode: '',
  claimProcessingTime: '',
  cashlessApproval: false,
  onlineClaimPortal: '',
  status: 'Active',
  remarks: ''
};

// Field limits (aligned with backend schema + DB column sizes)
const LIMITS = {
  tpaName: 150,
  insuranceProvider: 150,
  registrationNumber: 50,
  description: 500,
  contactPerson: 100,
  phone: 20,
  email: 150,
  url: 255,
  address: 255,
  location: 100,
  postalCode: 20,
  remarks: 500,
  claimMax: 365,
};

const insuranceProvidersList = [
  'Star Health Insurance',
  'HDFC Ergo',
  'CGHS',
  'ICICI Lombard',
  'Max Bupa'
];

const blockIntKeys = (e: KeyboardEvent<HTMLInputElement>) => {
  if (['e', 'E', '+', '-', '.'].includes(e.key)) e.preventDefault();
};

const mapApiToRecord = (item: Record<string, unknown>): TpaRecord => ({
  id:                  item.id                  as number,
  tpaCode:             item.tpaCode             as string,
  tpaName:             item.tpaName             as string,
  insuranceProvider:   item.insuranceProvider   as string,
  registrationNumber:  (item.registrationNumber as string) ?? '',
  description:         (item.description        as string) ?? '',
  contactPerson:       item.contactPerson       as string,
  phoneNumber:         item.phoneNumber         as string,
  alternatePhone:      (item.alternatePhone     as string) ?? '',
  email:               item.email               as string,
  website:             (item.website            as string) ?? '',
  addressLine1:        item.addressLine1        as string,
  addressLine2:        (item.addressLine2       as string) ?? '',
  country:             item.country             as string,
  state:               item.state               as string,
  city:                item.city                as string,
  postalCode:          item.postalCode          as string,
  claimProcessingTime: item.claimProcessingTime != null ? Number(item.claimProcessingTime) : '',
  cashlessApproval:    Boolean(item.cashlessApproval),
  onlineClaimPortal:   (item.onlineClaimPortal  as string) ?? '',
  status:              item.status              as string,
  remarks:             (item.remarks            as string) ?? '',
  createdBy:           (item.createdBy          as string) ?? undefined,
  createdDate:         item.createdDate ? String(item.createdDate).split('T')[0] : undefined,
  updatedBy:           (item.updatedBy          as string) ?? undefined,
  updatedDate:         item.updatedDate ? String(item.updatedDate).split('T')[0] : undefined,
});

export const TpaMaster = () => {
  const [records, setRecords] = useState<TpaRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [nextCode, setNextCode] = useState('');

  // Filter States
  const [showFilters, setShowFilters] = useState(false);
  const [filterProvider, setFilterProvider] = useState('');
  const [filterStatus, setFilterStatus] = useState('');

  // Form States
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState<TpaRecord | null>(null);
  const [formData, setFormData] = useState<TpaForm>(emptyData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // ── Fetch TPAs ───────────────────────────────────────────────
  const fetchTpas = async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/tpas/`);
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data: Record<string, unknown>[] = await res.json();
      setRecords(data.map(mapApiToRecord));
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Failed to load TPAs');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchTpas(); }, []);

  const fetchNextCode = async () => {
    setNextCode('');
    try {
      const res = await fetch(`${API_BASE}/tpas/next-code`);
      if (res.ok) {
        const data = await res.json();
        setNextCode(data.tpaCode ?? '');
      }
    } catch {
      setNextCode('');
    }
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.tpaName.trim()) newErrors.tpaName = 'TPA Name is required';
    if (!formData.insuranceProvider.trim()) newErrors.insuranceProvider = 'Insurance Provider is required';
    if (!formData.contactPerson.trim()) newErrors.contactPerson = 'Contact Person is required';

    if (!formData.phoneNumber.trim()) newErrors.phoneNumber = 'Phone Number is required';
    else if (!/^\d{10,15}$/.test(formData.phoneNumber.replace(/[\s+-]/g, ''))) newErrors.phoneNumber = 'Phone Number must be 10-15 digits';

    if (formData.alternatePhone.trim() && !/^\d{10,15}$/.test(formData.alternatePhone.replace(/[\s+-]/g, '')))
      newErrors.alternatePhone = 'Alternate Phone must be 10-15 digits';

    if (!formData.email.trim()) newErrors.email = 'Email is required';
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) newErrors.email = 'Valid Email is required';

    if (!formData.addressLine1.trim()) newErrors.addressLine1 = 'Address Line 1 is required';
    if (!formData.country.trim()) newErrors.country = 'Country is required';
    if (!formData.state.trim()) newErrors.state = 'State is required';
    if (!formData.city.trim()) newErrors.city = 'City is required';
    if (!formData.postalCode.trim()) newErrors.postalCode = 'Postal Code is required';

    if (formData.claimProcessingTime !== '' && Number(formData.claimProcessingTime) < 0)
      newErrors.claimProcessingTime = 'Cannot be negative';
    else if (formData.claimProcessingTime !== '' && Number(formData.claimProcessingTime) > LIMITS.claimMax)
      newErrors.claimProcessingTime = `Cannot exceed ${LIMITS.claimMax} days`;

    if (records.some(r => r.tpaName.toLowerCase() === formData.tpaName.trim().toLowerCase() && r.id !== selectedRecord?.id))
      newErrors.tpaName = 'TPA Name cannot be duplicated';

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleCreateNew = () => {
    setSelectedRecord(null);
    setFormData(emptyData);
    setErrors({});
    setIsFormOpen(true);
    fetchNextCode();
  };

  const handleEdit = (record: TpaRecord) => {
    setSelectedRecord(record);
    const { id, tpaCode, createdBy, createdDate, updatedBy, updatedDate, ...rest } = record;
    setFormData(rest);
    setErrors({});
    setIsFormOpen(true);
  };

  const handleDeleteRequest = (record: TpaRecord) => {
    setSelectedRecord(record);
    setIsDeleteOpen(true);
  };

  const handleSaveForm = async () => {
    if (!validateForm()) return;
    setIsSaving(true);
    setApiError(null);
    try {
      const body = {
        tpaName:             formData.tpaName.trim(),
        insuranceProvider:   formData.insuranceProvider,
        registrationNumber:  formData.registrationNumber || null,
        description:         formData.description || null,
        contactPerson:       formData.contactPerson.trim(),
        phoneNumber:         formData.phoneNumber.trim(),
        alternatePhone:      formData.alternatePhone || null,
        email:               formData.email.trim(),
        website:             formData.website || null,
        addressLine1:        formData.addressLine1.trim(),
        addressLine2:        formData.addressLine2 || null,
        country:             formData.country.trim(),
        state:               formData.state.trim(),
        city:                formData.city.trim(),
        postalCode:          formData.postalCode.trim(),
        claimProcessingTime: formData.claimProcessingTime === '' ? null : Number(formData.claimProcessingTime),
        cashlessApproval:    formData.cashlessApproval,
        onlineClaimPortal:   formData.onlineClaimPortal || null,
        status:              formData.status,
        remarks:             formData.remarks || null,
      };

      let res: Response;
      if (selectedRecord) {
        res = await fetch(`${API_BASE}/tpas/${selectedRecord.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, updatedBy: 'Admin' }),
        });
      } else {
        res = await fetch(`${API_BASE}/tpas/`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...body, createdBy: 'Admin' }),
        });
      }
      if (!res.ok) {
        const data = await res.json().catch(() => null);
        const detail = data && typeof data.detail === 'string' ? data.detail : `Save failed: ${res.status}`;
        throw new Error(detail);
      }

      await fetchTpas();
      setIsFormOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setIsSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!selectedRecord) return;
    setApiError(null);
    try {
      const res = await fetch(`${API_BASE}/tpas/${selectedRecord.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`Delete failed: ${res.status}`);
      await fetchTpas();
      setIsDeleteOpen(false);
      setSelectedRecord(null);
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : 'Delete failed');
      setIsDeleteOpen(false);
    }
  };

  const filteredRecords = records.filter(record => {
    const matchesSearch =
      record.tpaName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.tpaCode.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.contactPerson.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.phoneNumber.includes(searchTerm);

    const matchesProvider = !filterProvider || record.insuranceProvider === filterProvider;
    const matchesStatus = !filterStatus || record.status === filterStatus;

    return matchesSearch && matchesProvider && matchesStatus;
  });

  const inputCls = (err?: string) =>
    `w-full px-4 py-2 bg-slate-50 border rounded-xl text-sm focus:outline-none focus:ring-2 transition-all ${err ? 'border-red-300 focus:ring-red-200' : 'border-slate-200 focus:ring-primary/20'}`;

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="h-full flex flex-col relative"
    >
      {apiError && (
        <div className="mb-4 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span className="flex-1">{apiError}</span>
          <button onClick={() => setApiError(null)} className="text-red-500 hover:text-red-700 font-medium">Dismiss</button>
        </div>
      )}

      {!isFormOpen ? (
        <>
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-slate-800">TPA Master</h1>
              <p className="text-slate-500 mt-1"></p>
            </div>
            <div className="flex gap-3">
              <Button variant="outline" icon={RefreshCw} onClick={fetchTpas}>Refresh</Button>
              <Button variant="outline" icon={Download} onClick={() => exportToExcel(records, 'TpaMaster')}>Export</Button>
              <Button variant="filled" color="primary" icon={Plus} onClick={handleCreateNew}>
                Add TPA
              </Button>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex flex-wrap gap-4 items-center justify-between">
              <div className="relative flex-1 max-w-md">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search by Code, Name, Contact Person or Phone..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary text-sm"
                />
              </div>
              <Button
                variant={showFilters ? "filled" : "outline"}
                color="secondary"
                icon={Filter}
                onClick={() => setShowFilters(!showFilters)}
              >
                Filters
              </Button>
            </div>

            <AnimatePresence>
              {showFilters && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="border-b border-slate-200 bg-slate-50/50 p-4"
                >
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <select
                      value={filterProvider}
                      onChange={(e) => setFilterProvider(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Insurance Providers</option>
                      {insuranceProvidersList.map(ip => <option key={ip} value={ip}>{ip}</option>)}
                    </select>
                    <select
                      value={filterStatus}
                      onChange={(e) => setFilterStatus(e.target.value)}
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                    >
                      <option value="">All Statuses</option>
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="flex-1 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600">
                  <tr>
                    <th className="px-4 py-3 font-medium">TPA Code</th>
                    <th className="px-4 py-3 font-medium">TPA Name</th>
                    <th className="px-4 py-3 font-medium">Insurance Provider</th>
                    <th className="px-4 py-3 font-medium">Contact Person</th>
                    <th className="px-4 py-3 font-medium">Phone Number</th>
                    <th className="px-4 py-3 font-medium text-center">Status</th>
                    <th className="px-4 py-3 font-medium text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {isLoading ? (
                    <tr>
                      <td colSpan={7} className="px-4 py-8 text-center text-slate-500">
                        Loading TPAs...
                      </td>
                    </tr>
                  ) : filteredRecords.length > 0 ? (
                    filteredRecords.map((record) => (
                      <tr key={record.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-3 font-medium text-slate-800">{record.tpaCode}</td>
                        <td className="px-4 py-3 font-medium text-slate-800">{record.tpaName}</td>
                        <td className="px-4 py-3 text-slate-600">{record.insuranceProvider}</td>
                        <td className="px-4 py-3 text-slate-600">{record.contactPerson}</td>
                        <td className="px-4 py-3 text-slate-600">{record.phoneNumber}</td>
                        <td className="px-4 py-3 text-center">
                          <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${
                            record.status === 'Active'
                              ? 'bg-emerald-50 text-emerald-600 border border-emerald-200'
                              : 'bg-red-50 text-red-600 border border-red-200'
                          }`}>
                            {record.status}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => handleEdit(record)}
                              className="p-1.5 text-slate-400 hover:text-primary hover:bg-primary/5 rounded-lg transition-colors"
                              title="Edit"
                            >
                              <Edit2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteRequest(record)}
                              className="p-1.5 text-red-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={7} className="px-4 py-8 text-center text-slate-500">
                        No TPAs found matching your criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </>
      ) : (
        <>
          <div className="flex justify-between items-center mb-6">
            <div>
              <h1 className="text-2xl font-bold text-slate-800">
                {selectedRecord ? `Edit TPA: ${selectedRecord.tpaName}` : 'Add New TPA'}
              </h1>
              <p className="text-slate-500 text-sm">Configure Third Party Administrator details</p>
            </div>
          </div>

          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
            <div className="flex-1 overflow-y-auto p-5 space-y-4">
              {/* Basic Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Basic Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">TPA Code</label>
                    <input type="text" value={selectedRecord ? selectedRecord.tpaCode : (nextCode || 'Auto-generating…')} disabled readOnly className="w-full px-4 py-2 bg-slate-100 border border-slate-200 rounded-xl text-sm text-slate-500 cursor-not-allowed" />
                    {!selectedRecord && nextCode && (
                      <p className="text-slate-400 text-xs mt-1">Provisional — final code is assigned on save</p>
                    )}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">TPA Name <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.tpaName} value={formData.tpaName} onChange={e => setFormData({...formData, tpaName: e.target.value})} className={inputCls(errors.tpaName)} />
                    {errors.tpaName && <p className="text-red-500 text-xs mt-1">{errors.tpaName}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Insurance Provider <span className="text-red-500">*</span></label>
                    <select value={formData.insuranceProvider} onChange={e => setFormData({...formData, insuranceProvider: e.target.value})} className={inputCls(errors.insuranceProvider)}>
                      <option value="">Select Insurance Provider</option>
                      {insuranceProvidersList.map(type => <option key={type} value={type}>{type}</option>)}
                    </select>
                    {errors.insuranceProvider && <p className="text-red-500 text-xs mt-1">{errors.insuranceProvider}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Registration Number</label>
                    <input type="text" maxLength={LIMITS.registrationNumber} value={formData.registrationNumber} onChange={e => setFormData({...formData, registrationNumber: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Description</label>
                    <input type="text" maxLength={LIMITS.description} value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

              {/* Contact Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Contact Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Contact Person <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.contactPerson} value={formData.contactPerson} onChange={e => setFormData({...formData, contactPerson: e.target.value})} className={inputCls(errors.contactPerson)} />
                    {errors.contactPerson && <p className="text-red-500 text-xs mt-1">{errors.contactPerson}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Phone Number <span className="text-red-500">*</span></label>
                    <input type="tel" maxLength={LIMITS.phone} value={formData.phoneNumber} onChange={e => setFormData({...formData, phoneNumber: e.target.value})} className={inputCls(errors.phoneNumber)} />
                    {errors.phoneNumber && <p className="text-red-500 text-xs mt-1">{errors.phoneNumber}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Alternate Phone</label>
                    <input type="tel" maxLength={LIMITS.phone} value={formData.alternatePhone} onChange={e => setFormData({...formData, alternatePhone: e.target.value})} className={inputCls(errors.alternatePhone)} />
                    {errors.alternatePhone && <p className="text-red-500 text-xs mt-1">{errors.alternatePhone}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Email <span className="text-red-500">*</span></label>
                    <input type="email" maxLength={LIMITS.email} value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} className={inputCls(errors.email)} />
                    {errors.email && <p className="text-red-500 text-xs mt-1">{errors.email}</p>}
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Website</label>
                    <input type="url" maxLength={LIMITS.url} value={formData.website} onChange={e => setFormData({...formData, website: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

              {/* Address Information */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Address Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Address Line 1 <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.address} value={formData.addressLine1} onChange={e => setFormData({...formData, addressLine1: e.target.value})} className={inputCls(errors.addressLine1)} />
                    {errors.addressLine1 && <p className="text-red-500 text-xs mt-1">{errors.addressLine1}</p>}
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Address Line 2</label>
                    <input type="text" maxLength={LIMITS.address} value={formData.addressLine2} onChange={e => setFormData({...formData, addressLine2: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Country <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.location} value={formData.country} onChange={e => setFormData({...formData, country: e.target.value})} className={inputCls(errors.country)} />
                    {errors.country && <p className="text-red-500 text-xs mt-1">{errors.country}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">State <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.location} value={formData.state} onChange={e => setFormData({...formData, state: e.target.value})} className={inputCls(errors.state)} />
                    {errors.state && <p className="text-red-500 text-xs mt-1">{errors.state}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">City <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.location} value={formData.city} onChange={e => setFormData({...formData, city: e.target.value})} className={inputCls(errors.city)} />
                    {errors.city && <p className="text-red-500 text-xs mt-1">{errors.city}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Postal Code <span className="text-red-500">*</span></label>
                    <input type="text" maxLength={LIMITS.postalCode} value={formData.postalCode} onChange={e => setFormData({...formData, postalCode: e.target.value})} className={inputCls(errors.postalCode)} />
                    {errors.postalCode && <p className="text-red-500 text-xs mt-1">{errors.postalCode}</p>}
                  </div>
                </div>
              </section>

              {/* Claim Processing */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">Claim Processing</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Claim Processing Time (Days)</label>
                    <input type="number" min="0" max={LIMITS.claimMax} step="1" onKeyDown={blockIntKeys} value={formData.claimProcessingTime} onChange={e => setFormData({...formData, claimProcessingTime: e.target.value})} className={inputCls(errors.claimProcessingTime)} />
                    {errors.claimProcessingTime && <p className="text-red-500 text-xs mt-1">{errors.claimProcessingTime}</p>}
                  </div>
                  <div className="flex items-center gap-2">
                    <input type="checkbox" id="cashlessApproval" checked={formData.cashlessApproval} onChange={e => setFormData({...formData, cashlessApproval: e.target.checked})} className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary" />
                    <label htmlFor="cashlessApproval" className="text-sm font-medium text-slate-700">Cashless Approval</label>
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Online Claim Portal</label>
                    <input type="url" maxLength={LIMITS.url} value={formData.onlineClaimPortal} onChange={e => setFormData({...formData, onlineClaimPortal: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>

              {/* System */}
              <section>
                <h3 className="text-base font-bold text-slate-800 mb-3 border-b border-slate-100 pb-1.5">System</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Status <span className="text-red-500">*</span></label>
                    <select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20">
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Remarks</label>
                    <input type="text" maxLength={LIMITS.remarks} value={formData.remarks} onChange={e => setFormData({...formData, remarks: e.target.value})} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" />
                  </div>
                </div>
              </section>
            </div>

            <div className="p-4 border-t border-slate-100 bg-slate-50/50 flex justify-between items-center shrink-0">
              <Button variant="outline" color="secondary" onClick={() => setFormData(emptyData)} icon={RefreshCw}>
                Reset
              </Button>
              <div className="flex gap-3">
                <Button variant="outline" color="secondary" onClick={() => { setIsFormOpen(false); setSelectedRecord(null); }}>
                  Cancel
                </Button>
                <Button variant="filled" color="primary" onClick={handleSaveForm} icon={Save} disabled={isSaving}>
                  {isSaving ? 'Saving...' : (selectedRecord ? 'Update' : 'Save')}
                </Button>
              </div>
            </div>
          </div>
        </>
      )}

      <Modal
        isOpen={isDeleteOpen}
        onClose={() => setIsDeleteOpen(false)}
        title="Confirm Deletion"
        maxWidth="sm"
      >
        <div className="p-1">
          <div className="flex items-center gap-4 mb-6 text-amber-600 bg-amber-50 p-4 rounded-xl">
            <AlertTriangle className="w-8 h-8 shrink-0" />
            <p className="text-sm font-medium">
              Are you sure you want to delete TPA <strong>{selectedRecord?.tpaName}</strong>?
              This action cannot be undone.
            </p>
          </div>
          <div className="flex justify-end gap-3">
            <Button variant="outline" color="secondary" onClick={() => setIsDeleteOpen(false)}>
              Cancel
            </Button>
            <Button variant="filled" color="danger" onClick={confirmDelete}>
              Confirm Delete
            </Button>
          </div>
        </div>
      </Modal>
    </motion.div>
  );
};
