CREATE TABLE IF NOT EXISTS Billing_InsuranceClaim (
    ClaimId INT AUTO_INCREMENT PRIMARY KEY,
    ClaimNo VARCHAR(50) NOT NULL UNIQUE,
    ServiceOrderId INT NOT NULL,
    UHID VARCHAR(50) NOT NULL,
    ClaimAmount DECIMAL(10,2) NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'PENDING_CLAIM',
    ClaimDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    SubmissionDate DATETIME NULL,
    SettlementDate DATETIME NULL,
    SettledAmount DECIMAL(10,2) NULL,
    RejectionReason TEXT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted TINYINT(1) DEFAULT 0,
    FOREIGN KEY(ServiceOrderId) REFERENCES Service_Order(ServiceOrderId) ON DELETE CASCADE
);
