import re
from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from decimal import Decimal
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150
ACCOUNT_MAX  = 50
HOLDER_MAX   = 150
BRANCH_MAX   = 150
IFSC_MAX     = 20
SWIFT_MAX    = 20
CURRENCY_MAX = 10
REMARKS_MAX  = 500
BALANCE_MAX  = Decimal("9999999999999.99")   # DECIMAL(15,2)

_IFSC_RE  = re.compile(r"^[A-Z]{4}0[A-Z0-9]{6}$")
_SWIFT_RE = re.compile(r"^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$")


# ── Shared field rules ───────────────────────────────────────
class _BankFields(BaseModel):
    bankName:          str            = Field(max_length=NAME_MAX)
    accountNumber:     str            = Field(max_length=ACCOUNT_MAX)
    accountHolderName: str            = Field(max_length=HOLDER_MAX)
    branch:            str            = Field(max_length=BRANCH_MAX)
    ifscCode:          str            = Field(max_length=IFSC_MAX)
    swiftCode:         Optional[str]  = Field(default=None, max_length=SWIFT_MAX)
    currency:          str            = Field(default="INR", max_length=CURRENCY_MAX)
    openingBalance:    Decimal        = Decimal("0.00")
    status:            StatusEnum     = StatusEnum.Active
    remarks:           Optional[str]  = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("bankName", "accountNumber", "accountHolderName", "branch", "currency")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("ifscCode")
    @classmethod
    def valid_ifsc(cls, v: str) -> str:
        v = v.strip().upper()
        if not _IFSC_RE.match(v):
            raise ValueError("IFSC Code must be in format AAAA0NNNNNN (11 chars)")
        return v

    @field_validator("swiftCode")
    @classmethod
    def valid_swift(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip().upper()
        if not v:
            return None
        if not _SWIFT_RE.match(v):
            raise ValueError("SWIFT/BIC Code must be 8 or 11 characters")
        return v

    @field_validator("openingBalance")
    @classmethod
    def balance_in_range(cls, v: Decimal) -> Decimal:
        if abs(v) > BALANCE_MAX:
            raise ValueError("Opening Balance is out of range")
        return v


# ── Request: Create (code auto-generated by SP) ──────────────
class BankCreate(_BankFields):
    createdBy: Optional[str] = None


# ── Request: Update (BankCode is immutable) ──────────────────
class BankUpdate(_BankFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class BankResponse(BaseModel):
    id:                int
    bankCode:          str
    bankName:          str
    accountNumber:     str
    accountHolderName: str
    branch:            str
    ifscCode:          str
    swiftCode:         Optional[str]
    currency:          str
    openingBalance:    str
    status:            str
    remarks:           Optional[str]
    createdBy:         Optional[str]
    createdDate:       Optional[datetime]
    updatedBy:         Optional[str]
    updatedDate:       Optional[datetime]

    class Config:
        from_attributes = True
