from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX = 100
DESC_MAX = 500


# ── Shared field rules ───────────────────────────────────────
class _BrandFields(BaseModel):
    brandName:   str            = Field(max_length=NAME_MAX)
    description: Optional[str]  = Field(default=None, max_length=DESC_MAX)
    status:      StatusEnum     = StatusEnum.Active

    @field_validator("brandName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Brand Name is required and cannot be blank")
        return v.strip()

    @field_validator("description")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None


# ── Request: Create (code auto-generated by SP) ──────────────
class BrandCreate(_BrandFields):
    createdBy: Optional[str] = None


# ── Request: Update (BrandCode is immutable) ─────────────────
class BrandUpdate(_BrandFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class BrandResponse(BaseModel):
    id:          int
    brandCode:   str
    brandName:   str
    description: Optional[str]
    status:      str
    createdBy:   Optional[str]
    createdDate: Optional[datetime]
    updatedBy:   Optional[str]
    updatedDate: Optional[datetime]

    class Config:
        from_attributes = True
