from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Optional
from datetime import datetime
from decimal import Decimal
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150
HOSPITAL_MAX = 150
BRANCH_MAX   = 150
USER_MAX     = 150
REMARKS_MAX  = 500
AMOUNT_MAX   = Decimal("9999999999999.99")   # DECIMAL(15,2)


# ── Shared field rules ───────────────────────────────────────
class _CashCounterFields(BaseModel):
    counterName:      str            = Field(max_length=NAME_MAX)
    hospital:         str            = Field(max_length=HOSPITAL_MAX)
    branch:           str            = Field(max_length=BRANCH_MAX)
    assignedUser:     str            = Field(max_length=USER_MAX)
    openingBalance:   Decimal        = Decimal("0.00")
    maximumCashLimit: Decimal        = Decimal("0.00")
    status:           StatusEnum     = StatusEnum.Active
    remarks:          Optional[str]  = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("counterName", "hospital", "branch", "assignedUser")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("openingBalance", "maximumCashLimit")
    @classmethod
    def amount_in_range(cls, v: Decimal) -> Decimal:
        if v < 0:
            raise ValueError("Amount cannot be negative")
        if v > AMOUNT_MAX:
            raise ValueError("Amount is out of range")
        return v

    @model_validator(mode="after")
    def opening_within_limit(self):
        # If a maximum cash limit is set (> 0), the opening balance cannot exceed it.
        if self.maximumCashLimit > 0 and self.openingBalance > self.maximumCashLimit:
            raise ValueError("Opening Balance cannot exceed the Maximum Cash Limit")
        return self


# ── Request: Create (code auto-generated by SP) ──────────────
class CashCounterCreate(_CashCounterFields):
    createdBy: Optional[str] = None


# ── Request: Update (CounterCode is immutable) ───────────────
class CashCounterUpdate(_CashCounterFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class CashCounterResponse(BaseModel):
    id:               int
    counterCode:      str
    counterName:      str
    hospital:         str
    branch:           str
    assignedUser:     str
    openingBalance:   str
    maximumCashLimit: str
    status:           str
    remarks:          Optional[str]
    createdBy:        Optional[str]
    createdDate:      Optional[datetime]
    updatedBy:        Optional[str]
    updatedDate:      Optional[datetime]

    class Config:
        from_attributes = True
