from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX = 100
DESC_MAX = 500


# ── Shared field rules ───────────────────────────────────────
class _CategoryFields(BaseModel):
    categoryName: str            = Field(max_length=NAME_MAX)
    description:  Optional[str]  = Field(default=None, max_length=DESC_MAX)
    status:       StatusEnum     = StatusEnum.Active

    @field_validator("categoryName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Category Name is required and cannot be blank")
        return v.strip()

    @field_validator("description")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None


# ── Request: Create (code auto-generated by SP) ──────────────
class CategoryCreate(_CategoryFields):
    createdBy: Optional[str] = None


# ── Request: Update (CategoryCode is immutable) ──────────────
class CategoryUpdate(_CategoryFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class CategoryResponse(BaseModel):
    id:           int
    categoryCode: str
    categoryName: str
    description:  Optional[str]
    status:       str
    createdBy:    Optional[str]
    createdDate:  Optional[datetime]
    updatedBy:    Optional[str]
    updatedDate:  Optional[datetime]

    class Config:
        from_attributes = True
