from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX = 100
DESC_MAX = 500
INVTYPE_MAX = 50

INVENTORY_TYPES = {"Medical", "Non-Medical", "Asset", "Service"}


# ── Shared field rules ───────────────────────────────────────
class _CategoryFields(BaseModel):
    categoryName:  str           = Field(max_length=NAME_MAX)
    inventoryType: Optional[str] = Field(default=None, max_length=INVTYPE_MAX)
    description:   Optional[str] = Field(default=None, max_length=DESC_MAX)

    # Handling rules every item in this category inherits.
    stockRequired:   bool = True
    batchTracking:   bool = False
    expiryTracking:  bool = False
    barcodeRequired: bool = False

    remarks:      Optional[str]  = Field(default=None, max_length=DESC_MAX)
    status:       StatusEnum     = StatusEnum.Active

    @field_validator("categoryName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Category Name is required and cannot be blank")
        return v.strip()

    @field_validator("description", "remarks", "inventoryType")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("inventoryType")
    @classmethod
    def known_type(cls, v: Optional[str]) -> Optional[str]:
        if v and v not in INVENTORY_TYPES:
            raise ValueError(f"Inventory Type must be one of: {', '.join(sorted(INVENTORY_TYPES))}")
        return v

    @model_validator(mode="after")
    def tracking_is_coherent(self):
        # Mirrors the SP guards so the caller gets a field-level message rather
        # than a raw SQL signal.
        if self.expiryTracking and not self.batchTracking:
            raise ValueError("Expiry tracking requires batch tracking")
        if not self.stockRequired and (self.batchTracking or self.expiryTracking):
            raise ValueError("Batch and expiry tracking only apply to stocked categories")
        return self


# ── Request: Create (code auto-generated by SP) ──────────────
class CategoryCreate(_CategoryFields):
    createdBy: Optional[str] = None


# ── Request: Update (CategoryCode is immutable) ──────────────
class CategoryUpdate(_CategoryFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class CategoryResponse(BaseModel):
    id:           int
    categoryCode:  str
    categoryName:  str
    inventoryType: Optional[str]
    description:   Optional[str]
    stockRequired:   bool
    batchTracking:   bool
    expiryTracking:  bool
    barcodeRequired: bool
    remarks:      Optional[str]
    status:       str
    createdBy:    Optional[str]
    createdDate:  Optional[datetime]
    updatedBy:    Optional[str]
    updatedDate:  Optional[datetime]

    class Config:
        from_attributes = True
