from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX = 100
DESC_MAX = 500
INVTYPE_MAX = 50

# Canonical inventory types. MEDICINE is owned by Master_Medicine; the other
# two are owned by Master_Item. These exact strings are the only spelling of
# this concept used across DB, API and UI.
INVENTORY_TYPES = {"MEDICINE", "MEDICAL_ITEM", "NON_MEDICAL"}

# Values written before the unified-inventory migration. Accepted on input and
# translated, so an older client or a saved form does not start failing.
LEGACY_INVENTORY_TYPES = {
    "Medical": "MEDICAL_ITEM",
    "Non-Medical": "NON_MEDICAL",
    "Asset": "NON_MEDICAL",
    "Service": "NON_MEDICAL",
}


# ── Shared field rules ───────────────────────────────────────
class _CategoryFields(BaseModel):
    categoryName:  str           = Field(max_length=NAME_MAX)
    inventoryType: Optional[str] = Field(default=None, max_length=INVTYPE_MAX)
    description:   Optional[str] = Field(default=None, max_length=DESC_MAX)

    # Handling rules every item in this category inherits.
    stockRequired:   bool = True
    batchTracking:   bool = False
    expiryTracking:  bool = False
    barcodeRequired: bool = False

    remarks:      Optional[str]  = Field(default=None, max_length=DESC_MAX)
    status:       StatusEnum     = StatusEnum.Active

    @field_validator("categoryName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Category Name is required and cannot be blank")
        return v.strip()

    @field_validator("description", "remarks", "inventoryType")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("inventoryType")
    @classmethod
    def known_type(cls, v: Optional[str]) -> Optional[str]:
        if not v:
            raise ValueError(
                f"Inventory Type is required: {', '.join(sorted(INVENTORY_TYPES))}")
        v = LEGACY_INVENTORY_TYPES.get(v, v)
        if v not in INVENTORY_TYPES:
            raise ValueError(f"Inventory Type must be one of: {', '.join(sorted(INVENTORY_TYPES))}")
        return v

    @model_validator(mode="after")
    def tracking_is_coherent(self):
        # Mirrors the SP guards so the caller gets a field-level message rather
        # than a raw SQL signal.
        if self.expiryTracking and not self.batchTracking:
            raise ValueError("Expiry tracking requires batch tracking")
        if not self.stockRequired and (self.batchTracking or self.expiryTracking):
            raise ValueError("Batch and expiry tracking only apply to stocked categories")
        return self


# ── Request: Create (code auto-generated by SP) ──────────────
class CategoryCreate(_CategoryFields):
    createdBy: Optional[str] = None


# ── Request: Update (CategoryCode is immutable) ──────────────
class CategoryUpdate(_CategoryFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class CategoryResponse(BaseModel):
    id:           int
    categoryCode:  str
    categoryName:  str
    inventoryType: Optional[str]
    description:   Optional[str]
    stockRequired:   bool
    batchTracking:   bool
    expiryTracking:  bool
    barcodeRequired: bool
    remarks:      Optional[str]
    status:       str
    createdBy:    Optional[str]
    createdDate:  Optional[datetime]
    updatedBy:    Optional[str]
    updatedDate:  Optional[datetime]

    class Config:
        from_attributes = True
