from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from decimal import Decimal
from enum import Enum


class AccountTypeEnum(str, Enum):
    Asset     = "Asset"
    Liability = "Liability"
    Income    = "Income"
    Expense   = "Expense"
    Equity    = "Equity"


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX    = 150
PARENT_MAX  = 150
DESC_MAX    = 500
REMARKS_MAX = 500
BALANCE_MAX = Decimal("9999999999999.99")   # DECIMAL(15,2)


# ── Shared field rules ───────────────────────────────────────
class _CoaFields(BaseModel):
    accountName:            str                = Field(max_length=NAME_MAX)
    accountType:            AccountTypeEnum
    parentAccount:          Optional[str]      = Field(default=None, max_length=PARENT_MAX)
    description:            Optional[str]       = Field(default=None, max_length=DESC_MAX)
    openingBalance:         Decimal            = Decimal("0.00")
    allowManualJournal:     bool               = True
    reconciliationRequired: bool               = False
    status:                 StatusEnum         = StatusEnum.Active
    remarks:                Optional[str]       = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("accountName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Account Name is required and cannot be blank")
        return v.strip()

    @field_validator("parentAccount", "description", "remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("openingBalance")
    @classmethod
    def balance_in_range(cls, v: Decimal) -> Decimal:
        # Opening balance may be negative (e.g. contra accounts), but must fit DECIMAL(15,2).
        if abs(v) > BALANCE_MAX:
            raise ValueError("Opening Balance is out of range")
        return v


# ── Request: Create (code auto-generated by SP) ──────────────
class CoaCreate(_CoaFields):
    createdBy: Optional[str] = None


# ── Request: Update (AccountCode is immutable) ───────────────
class CoaUpdate(_CoaFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class CoaResponse(BaseModel):
    id:                     int
    accountCode:            str
    accountName:            str
    accountType:            str
    parentAccount:          Optional[str]
    description:            Optional[str]
    openingBalance:         str
    allowManualJournal:     bool
    reconciliationRequired: bool
    status:                 str
    remarks:                Optional[str]
    createdBy:              Optional[str]
    createdDate:            Optional[datetime]
    updatedBy:              Optional[str]
    updatedDate:            Optional[datetime]

    class Config:
        from_attributes = True
