from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX    = 150
DEPT_MAX    = 100
MANAGER_MAX = 100
DESC_MAX    = 500
REMARKS_MAX = 500


# ── Shared field rules ───────────────────────────────────────
class _CostCenterFields(BaseModel):
    costCenterName: str            = Field(max_length=NAME_MAX)
    department:     str            = Field(max_length=DEPT_MAX)
    manager:        Optional[str]  = Field(default=None, max_length=MANAGER_MAX)
    description:    Optional[str]  = Field(default=None, max_length=DESC_MAX)
    status:         StatusEnum     = StatusEnum.Active
    remarks:        Optional[str]  = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("costCenterName", "department")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("manager", "description", "remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None


# ── Request: Create (code auto-generated by SP) ──────────────
class CostCenterCreate(_CostCenterFields):
    createdBy: Optional[str] = None


# ── Request: Update (CostCenterCode is immutable) ────────────
class CostCenterUpdate(_CostCenterFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class CostCenterResponse(BaseModel):
    id:             int
    costCenterCode: str
    costCenterName: str
    department:     str
    manager:        Optional[str]
    description:    Optional[str]
    status:         str
    remarks:        Optional[str]
    createdBy:      Optional[str]
    createdDate:    Optional[datetime]
    updatedBy:      Optional[str]
    updatedDate:    Optional[datetime]

    class Config:
        from_attributes = True
