from pydantic import BaseModel
from typing import Optional
from datetime import datetime
from enum import Enum


class DepartmentTypeEnum(str, Enum):
    Clinical    = "Clinical"
    NonClinical = "Non-Clinical"


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Request: Create (no code — auto-generated by SP) ─────────
class DepartmentCreate(BaseModel):
    departmentName: str
    departmentType: DepartmentTypeEnum = DepartmentTypeEnum.Clinical
    description:    Optional[str]      = None
    departmentHead: Optional[str]      = None
    consultationFee: Optional[float]   = None
    status:         StatusEnum         = StatusEnum.Active
    createdBy:      Optional[str]      = None


# ── Request: Update (code is immutable) ──────────────────────
class DepartmentUpdate(BaseModel):
    departmentName: str
    departmentType: DepartmentTypeEnum = DepartmentTypeEnum.Clinical
    description:    Optional[str]      = None
    departmentHead: Optional[str]      = None
    consultationFee: Optional[float]   = None
    status:         StatusEnum         = StatusEnum.Active
    updatedBy:      Optional[str]      = None


# ── Response ─────────────────────────────────────────────────
class DepartmentResponse(BaseModel):
    id:             int
    departmentCode: str
    departmentName: str
    departmentType: str
    description:    Optional[str]
    departmentHead: Optional[str]
    consultationFee: Optional[float] = None
    doctorsCount:    int             = 0
    status:         str
    createdBy:      Optional[str]
    createdDate:    Optional[datetime]
    updatedBy:      Optional[str]
    updatedDate:    Optional[datetime]

    class Config:
        from_attributes = True
