from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX = 100
DEPT_MAX = 100
DESC_MAX = 500


# ── Shared field rules ───────────────────────────────────────
class _SpecializationFields(BaseModel):
    specializationName: str           = Field(max_length=NAME_MAX)
    departmentName:     Optional[str] = Field(default=None, max_length=DEPT_MAX)
    description:        Optional[str] = Field(default=None, max_length=DESC_MAX)
    status:             StatusEnum    = StatusEnum.Active

    @field_validator("specializationName")
    @classmethod
    def name_valid(cls, v: str) -> str:
        v = (v or "").strip()
        if not v:
            raise ValueError("Specialization Name is required and cannot be blank")
        # Letters, spaces and the punctuation real specialities use
        # ("Ear, Nose & Throat", "Obstetrics/Gynaecology", "Paediatrics - Neonatal").
        if not all(c.isalpha() or c in " ,&/()-." for c in v):
            raise ValueError("Specialization Name may only contain letters, spaces and , & / ( ) - .")
        return v

    @field_validator("departmentName", "description")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None


# ── Request: Create (code auto-generated by SP) ──────────────
class DoctorSpecializationCreate(_SpecializationFields):
    createdBy: Optional[str] = None


# ── Request: Update (SpecializationCode is immutable) ────────
class DoctorSpecializationUpdate(_SpecializationFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class DoctorSpecializationResponse(BaseModel):
    id:                 int
    specializationCode: str
    specializationName: str
    departmentName:     Optional[str]
    description:        Optional[str]
    status:             str
    createdBy:          Optional[str]
    createdDate:        Optional[datetime]
    updatedBy:          Optional[str]
    updatedDate:        Optional[datetime]

    class Config:
        from_attributes = True
