from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Optional
from datetime import datetime, date
from decimal import Decimal
from enum import Enum


class CalibrationScheduleEnum(str, Enum):
    Monthly   = "Monthly"
    Quarterly = "Quarterly"
    BiAnnual  = "Bi-Annual"
    Annual    = "Annual"


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150
MFR_MAX      = 100
MODEL_MAX    = 100
SERIAL_MAX   = 100
SUPPLIER_MAX = 150
VENDOR_MAX   = 150
LOC_MAX      = 100   # hospital / branch / department
ROOM_MAX     = 50
REMARKS_MAX  = 500   # DB TEXT (capped for consistency with UI)
COST_MAX     = Decimal("999999999999.99")   # DB DECIMAL(14,2)


# ── Shared field rules ───────────────────────────────────────
class _EquipmentFields(BaseModel):
    equipmentName:       str                        = Field(max_length=NAME_MAX)
    manufacturer:        str                        = Field(max_length=MFR_MAX)
    model:               str                        = Field(max_length=MODEL_MAX)
    serialNumber:        str                        = Field(max_length=SERIAL_MAX)

    purchaseDate:        date
    warrantyExpiryDate:  Optional[date]             = None
    supplier:            Optional[str]              = Field(default=None, max_length=SUPPLIER_MAX)
    purchaseCost:        Optional[Decimal]          = None

    calibrationSchedule: CalibrationScheduleEnum
    nextMaintenanceDate: date
    maintenanceVendor:   Optional[str]              = Field(default=None, max_length=VENDOR_MAX)
    lastServiceDate:     Optional[date]             = None

    hospital:            str                        = Field(max_length=LOC_MAX)
    branch:              str                        = Field(max_length=LOC_MAX)
    department:          str                        = Field(max_length=LOC_MAX)
    roomNumber:          Optional[str]              = Field(default=None, max_length=ROOM_MAX)

    status:              StatusEnum                 = StatusEnum.Active
    remarks:             Optional[str]              = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("equipmentName", "manufacturer", "model", "serialNumber",
                     "hospital", "branch", "department")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("supplier", "maintenanceVendor", "roomNumber", "remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("purchaseCost")
    @classmethod
    def cost_in_range(cls, v: Optional[Decimal]) -> Optional[Decimal]:
        if v is None:
            return None
        if v < 0:
            raise ValueError("Purchase Cost cannot be negative")
        if v > COST_MAX:
            raise ValueError(f"Purchase Cost cannot exceed {COST_MAX}")
        return v

    @model_validator(mode="after")
    def check_dates(self):
        today = date.today()

        if self.purchaseDate > today:
            raise ValueError("Purchase Date cannot be in the future")

        if self.nextMaintenanceDate <= self.purchaseDate:
            raise ValueError("Next Maintenance Date must be after Purchase Date")

        if self.warrantyExpiryDate and self.warrantyExpiryDate < self.purchaseDate:
            raise ValueError("Warranty Expiry Date cannot be before Purchase Date")

        if self.lastServiceDate:
            if self.lastServiceDate < self.purchaseDate:
                raise ValueError("Last Service Date cannot be before Purchase Date")
            if self.lastServiceDate > today:
                raise ValueError("Last Service Date cannot be in the future")

        return self


# ── Request: Create (code auto-generated by SP) ──────────────
class EquipmentCreate(_EquipmentFields):
    createdBy: Optional[str] = None


# ── Request: Update (EquipmentCode is immutable) ─────────────
class EquipmentUpdate(_EquipmentFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
# Dates are returned as 'YYYY-MM-DD' strings and cost as a string so the
# payload matches the EquipmentRecord interface used by EquipmentMaster.tsx.
class EquipmentResponse(BaseModel):
    id:                  int
    equipmentCode:       str
    equipmentName:       str
    manufacturer:        str
    model:               str
    serialNumber:        str
    purchaseDate:        Optional[str]
    warrantyExpiryDate:  Optional[str]
    supplier:            Optional[str]
    purchaseCost:        Optional[str]
    calibrationSchedule: str
    nextMaintenanceDate: Optional[str]
    maintenanceVendor:   Optional[str]
    lastServiceDate:     Optional[str]
    hospital:            str
    branch:              str
    department:          str
    roomNumber:          Optional[str]
    status:              str
    remarks:             Optional[str]
    createdBy:           Optional[str]
    createdDate:         Optional[datetime]
    updatedBy:           Optional[str]
    updatedDate:         Optional[datetime]

    class Config:
        from_attributes = True
