import re
from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class InsuranceTypeEnum(str, Enum):
    Health       = "Health Insurance"
    Corporate    = "Corporate Insurance"
    Government    = "Government Health Scheme"
    Accident      = "Accident Insurance"
    Employee      = "Employee Health Plan"
    International  = "International Insurance"


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150
REG_MAX      = 50
DESC_MAX     = 500
CONTACT_MAX  = 100
PHONE_MAX    = 20
EMAIL_MAX    = 150
URL_MAX      = 255
ADDR_MAX     = 255
LOC_MAX      = 100
POSTAL_MAX   = 20
REMARKS_MAX  = 500
SETTLE_MAX   = 365   # days

_EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")
_PHONE_RE = re.compile(r"^\d{10,15}$")


# ── Shared field rules ───────────────────────────────────────
class _InsuranceProviderFields(BaseModel):
    providerName:        str                = Field(max_length=NAME_MAX)
    insuranceType:       InsuranceTypeEnum
    registrationNumber:  Optional[str]      = Field(default=None, max_length=REG_MAX)
    description:         Optional[str]       = Field(default=None, max_length=DESC_MAX)

    contactPerson:       str                = Field(max_length=CONTACT_MAX)
    phoneNumber:         str                = Field(max_length=PHONE_MAX)
    alternatePhone:      Optional[str]      = Field(default=None, max_length=PHONE_MAX)
    email:               str                = Field(max_length=EMAIL_MAX)
    website:             Optional[str]      = Field(default=None, max_length=URL_MAX)

    addressLine1:        str                = Field(max_length=ADDR_MAX)
    addressLine2:        Optional[str]      = Field(default=None, max_length=ADDR_MAX)
    country:             str                = Field(max_length=LOC_MAX)
    state:               str                = Field(max_length=LOC_MAX)
    city:                str                = Field(max_length=LOC_MAX)
    postalCode:          str                = Field(max_length=POSTAL_MAX)

    claimPortalUrl:      Optional[str]      = Field(default=None, max_length=URL_MAX)
    cashlessFacility:    bool               = False
    preAuthRequired:     bool               = True
    claimSettlementDays: Optional[int]      = None

    status:              StatusEnum         = StatusEnum.Active
    remarks:             Optional[str]      = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("providerName", "contactPerson", "addressLine1",
                     "country", "state", "city", "postalCode")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("registrationNumber", "description", "alternatePhone",
                     "website", "addressLine2", "claimPortalUrl", "remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("phoneNumber")
    @classmethod
    def valid_phone(cls, v: str) -> str:
        digits = re.sub(r"[\s+\-]", "", v)
        if not _PHONE_RE.match(digits):
            raise ValueError("Phone Number must be 10-15 digits")
        return v.strip()

    @field_validator("alternatePhone")
    @classmethod
    def valid_alt_phone(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        if not v:
            return None
        digits = re.sub(r"[\s+\-]", "", v)
        if not _PHONE_RE.match(digits):
            raise ValueError("Alternate Phone must be 10-15 digits")
        return v

    @field_validator("email")
    @classmethod
    def valid_email(cls, v: str) -> str:
        v = v.strip()
        if not _EMAIL_RE.match(v):
            raise ValueError("A valid Email is required")
        return v

    @field_validator("claimSettlementDays")
    @classmethod
    def settlement_in_range(cls, v: Optional[int]) -> Optional[int]:
        if v is None:
            return None
        if v < 0:
            raise ValueError("Claim Settlement Days cannot be negative")
        if v > SETTLE_MAX:
            raise ValueError(f"Claim Settlement Days cannot exceed {SETTLE_MAX}")
        return v


# ── Request: Create (code auto-generated by SP) ──────────────
class InsuranceProviderCreate(_InsuranceProviderFields):
    createdBy: Optional[str] = None


# ── Request: Update (ProviderCode is immutable) ──────────────
class InsuranceProviderUpdate(_InsuranceProviderFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class InsuranceProviderResponse(BaseModel):
    id:                  int
    providerCode:        str
    providerName:        str
    insuranceType:       str
    registrationNumber:  Optional[str]
    description:         Optional[str]
    contactPerson:       str
    phoneNumber:         str
    alternatePhone:      Optional[str]
    email:               str
    website:             Optional[str]
    addressLine1:        str
    addressLine2:        Optional[str]
    country:             str
    state:               str
    city:                str
    postalCode:          str
    claimPortalUrl:      Optional[str]
    cashlessFacility:    bool
    preAuthRequired:     bool
    claimSettlementDays: Optional[int]
    status:              str
    remarks:             Optional[str]
    createdBy:           Optional[str]
    createdDate:         Optional[datetime]
    updatedBy:           Optional[str]
    updatedDate:         Optional[datetime]

    class Config:
        from_attributes = True
