from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 200
CATEGORY_MAX = 100
SUBCAT_MAX   = 100
DEPT_MAX     = 100
BRAND_MAX    = 100
MFR_MAX      = 150
VENDOR_MAX   = 150
UOM_MAX      = 50
HSN_MAX      = 20
BARCODE_MAX  = 50
DESC_MAX     = 500
GST_MAX      = 100
STOCK_MAX    = 1_000_000
SHELF_MAX    = 36_500   # ~100 years in days


# ── Shared field rules ───────────────────────────────────────
class _ItemFields(BaseModel):
    itemName:        str            = Field(max_length=NAME_MAX)
    category:        str            = Field(max_length=CATEGORY_MAX)
    subCategory:     Optional[str]  = Field(default=None, max_length=SUBCAT_MAX)
    department:      Optional[str]  = Field(default=None, max_length=DEPT_MAX)
    brand:           Optional[str]  = Field(default=None, max_length=BRAND_MAX)
    manufacturer:    Optional[str]  = Field(default=None, max_length=MFR_MAX)
    vendor:          Optional[str]  = Field(default=None, max_length=VENDOR_MAX)
    uom:             str            = Field(max_length=UOM_MAX)

    hsnCode:         Optional[str]  = Field(default=None, max_length=HSN_MAX)
    gstPercentage:   int            = 0

    reorderLevel:    Optional[int]  = None
    minStock:        Optional[int]  = None
    maxStock:        Optional[int]  = None
    shelfLife:       Optional[int]  = None
    batchRequired:   bool           = False
    expiryRequired:  bool           = False

    barcode:         Optional[str]  = Field(default=None, max_length=BARCODE_MAX)
    itemDescription: Optional[str]  = Field(default=None, max_length=DESC_MAX)

    status:          StatusEnum     = StatusEnum.Active

    @field_validator("itemName", "category", "uom")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("subCategory", "department", "brand", "manufacturer",
                     "vendor", "hsnCode", "barcode", "itemDescription")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("gstPercentage")
    @classmethod
    def gst_in_range(cls, v: int) -> int:
        if v < 0 or v > GST_MAX:
            raise ValueError(f"GST Percentage must be between 0 and {GST_MAX}")
        return v

    @field_validator("reorderLevel", "minStock", "maxStock")
    @classmethod
    def stock_in_range(cls, v: Optional[int]) -> Optional[int]:
        if v is None:
            return None
        if v < 0:
            raise ValueError("Stock values cannot be negative")
        if v > STOCK_MAX:
            raise ValueError(f"Stock values cannot exceed {STOCK_MAX}")
        return v

    @field_validator("shelfLife")
    @classmethod
    def shelf_in_range(cls, v: Optional[int]) -> Optional[int]:
        if v is None:
            return None
        if v < 0:
            raise ValueError("Shelf Life cannot be negative")
        if v > SHELF_MAX:
            raise ValueError(f"Shelf Life cannot exceed {SHELF_MAX} days")
        return v

    @model_validator(mode="after")
    def stock_consistency(self):
        if self.minStock is not None and self.maxStock is not None and self.maxStock < self.minStock:
            raise ValueError("Max Stock cannot be less than Min Stock")
        return self


# ── Request: Create (code auto-generated by SP) ──────────────
class ItemCreate(_ItemFields):
    createdBy: Optional[str] = None


# ── Request: Update (ItemCode is immutable) ──────────────────
class ItemUpdate(_ItemFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class ItemResponse(BaseModel):
    id:              int
    itemCode:        str
    itemName:        str
    category:        str
    subCategory:     Optional[str]
    department:      Optional[str]
    brand:           Optional[str]
    manufacturer:    Optional[str]
    vendor:          Optional[str]
    uom:             str
    hsnCode:         Optional[str]
    gstPercentage:   int
    reorderLevel:    Optional[int]
    minStock:        Optional[int]
    maxStock:        Optional[int]
    shelfLife:       Optional[int]
    batchRequired:   bool
    expiryRequired:  bool
    barcode:         Optional[str]
    itemDescription: Optional[str]
    status:          str
    createdBy:       Optional[str]
    createdDate:     Optional[datetime]
    updatedBy:       Optional[str]
    updatedDate:     Optional[datetime]

    class Config:
        from_attributes = True
