from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX    = 150
CONTACT_MAX = 150
ADDR_MAX    = 255
COUNTRY_MAX = 100


# ── Shared field rules ───────────────────────────────────────
class _ManufacturerFields(BaseModel):
    manufacturerName: str            = Field(max_length=NAME_MAX)
    contactDetails:   Optional[str]  = Field(default=None, max_length=CONTACT_MAX)
    address:          Optional[str]  = Field(default=None, max_length=ADDR_MAX)
    country:          Optional[str]  = Field(default=None, max_length=COUNTRY_MAX)
    status:           StatusEnum     = StatusEnum.Active

    @field_validator("manufacturerName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Manufacturer Name is required and cannot be blank")
        return v.strip()

    @field_validator("contactDetails", "address", "country")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None


# ── Request: Create (code auto-generated by SP) ──────────────
class ManufacturerCreate(_ManufacturerFields):
    createdBy: Optional[str] = None


# ── Request: Update (ManufacturerCode is immutable) ──────────
class ManufacturerUpdate(_ManufacturerFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class ManufacturerResponse(BaseModel):
    id:               int
    manufacturerCode: str
    manufacturerName: str
    contactDetails:   Optional[str]
    address:          Optional[str]
    country:          Optional[str]
    status:           str
    createdBy:        Optional[str]
    createdDate:      Optional[datetime]
    updatedBy:        Optional[str]
    updatedDate:      Optional[datetime]

    class Config:
        from_attributes = True
