from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX    = 150
DEPT_MAX    = 100
DESC_MAX    = 500
REMARKS_MAX = 500


# ── Shared field rules ───────────────────────────────────────
class _ProfitCenterFields(BaseModel):
    profitCenterName: str            = Field(max_length=NAME_MAX)
    department:       str            = Field(max_length=DEPT_MAX)
    description:      Optional[str]  = Field(default=None, max_length=DESC_MAX)
    status:          StatusEnum      = StatusEnum.Active
    remarks:         Optional[str]   = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("profitCenterName", "department")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("description", "remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None


# ── Request: Create (code auto-generated by SP) ──────────────
class ProfitCenterCreate(_ProfitCenterFields):
    createdBy: Optional[str] = None


# ── Request: Update (ProfitCenterCode is immutable) ──────────
class ProfitCenterUpdate(_ProfitCenterFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class ProfitCenterResponse(BaseModel):
    id:               int
    profitCenterCode: str
    profitCenterName: str
    department:       str
    description:      Optional[str]
    status:           str
    remarks:          Optional[str]
    createdBy:        Optional[str]
    createdDate:      Optional[datetime]
    updatedBy:        Optional[str]
    updatedDate:      Optional[datetime]

    class Config:
        from_attributes = True
