from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from decimal import Decimal
from enum import Enum


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150            # DB VARCHAR(255)
DEPT_MAX     = 100            # DB VARCHAR(100)
DESC_MAX     = 500            # DB VARCHAR(500)
TEMPLATE_MAX = 255            # DB VARCHAR(255)
REMARKS_MAX  = 500            # DB TEXT (capped for consistency with UI)
DURATION_MAX = 1440          # minutes (24 h)
TAT_MAX      = 720            # hours (30 days)
PRICE_MAX    = Decimal("9999999")   # DB DECIMAL(12,2)


class ServiceCategoryEnum(str, Enum):
    XRay       = "X-Ray"
    CTScan     = "CT Scan"
    MRI        = "MRI"
    Ultrasound = "Ultrasound"
    Mammogram  = "Mammogram"
    ECG        = "ECG"
    Echo       = "Echo"
    PETScan    = "PET Scan"


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Shared field rules ───────────────────────────────────────
class _RadiologyServiceFields(BaseModel):
    serviceName:          str               = Field(max_length=NAME_MAX)
    description:          Optional[str]     = Field(default=None, max_length=DESC_MAX)
    serviceCategory:      ServiceCategoryEnum
    estimatedDuration:    int                       # Minutes, 1 - 1440
    reportTat:            int                       # Hours,   1 - 720
    requiresAppointment:  bool          = True
    requiresContrast:     bool          = False
    requiresFasting:      bool          = False
    servicePrice:         Decimal                   # 0 < price <= 9,999,999
    gst:                  Optional[Decimal] = None  # 0 - 100 (%)
    reportTemplate:       Optional[str]     = Field(default=None, max_length=TEMPLATE_MAX)
    requiresApproval:     bool          = True
    criticalFindingAlert: bool          = False
    status:               StatusEnum    = StatusEnum.Active
    remarks:              Optional[str]     = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("serviceName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("description", "reportTemplate", "remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("estimatedDuration")
    @classmethod
    def duration_positive(cls, v: int) -> int:
        if v <= 0:
            raise ValueError("Duration must be greater than zero")
        if v > DURATION_MAX:
            raise ValueError(f"Duration cannot exceed {DURATION_MAX} minutes")
        return v

    @field_validator("reportTat")
    @classmethod
    def tat_positive(cls, v: int) -> int:
        if v <= 0:
            raise ValueError("Turnaround Time must be greater than zero")
        if v > TAT_MAX:
            raise ValueError(f"Turnaround Time cannot exceed {TAT_MAX} hours")
        return v

    @field_validator("servicePrice")
    @classmethod
    def price_positive(cls, v: Decimal) -> Decimal:
        if v <= 0:
            raise ValueError("Price must be greater than zero")
        if v > PRICE_MAX:
            raise ValueError(f"Price cannot exceed {PRICE_MAX}")
        return v

    @field_validator("gst")
    @classmethod
    def gst_in_range(cls, v: Optional[Decimal]) -> Optional[Decimal]:
        if v is None:
            return None
        if v < 0 or v > 100:
            raise ValueError("GST/Tax must be between 0 and 100")
        return v


# ── Request: Create (no code — auto-generated by SP) ─────────
class RadiologyServiceCreate(_RadiologyServiceFields):
    createdBy: Optional[str] = None


# ── Request: Update (ServiceCode is immutable) ───────────────
class RadiologyServiceUpdate(_RadiologyServiceFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
# Numeric fields are returned as strings so the payload matches the
# RadiologyServiceRecord interface used by RadiologyServiceMaster.tsx.
class RadiologyServiceResponse(BaseModel):
    id:                   int
    serviceCode:          str
    serviceName:          str
    description:          Optional[str]
    serviceCategory:      str
    estimatedDuration:    str
    reportTat:            str
    requiresAppointment:  bool
    requiresContrast:     bool
    requiresFasting:      bool
    servicePrice:         str
    gst:                  Optional[str]
    reportTemplate:       Optional[str]
    requiresApproval:     bool
    criticalFindingAlert: bool
    status:               str
    remarks:              Optional[str]
    createdBy:            Optional[str]
    createdDate:          Optional[datetime]
    updatedBy:            Optional[str]
    updatedDate:          Optional[datetime]

    class Config:
        from_attributes = True
