from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Optional
from datetime import datetime
from decimal import Decimal
from enum import Enum


class TaxEnum(str, Enum):
    GST5  = "GST 5%"
    GST12 = "GST 12%"
    GST18 = "GST 18%"


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150
CATEGORY_MAX = 100
DEPT_MAX     = 100
DESC_MAX     = 500
REMARKS_MAX  = 500
PRICE_MAX    = Decimal("9999999")   # DB DECIMAL(12,2)


# ── Shared field rules ───────────────────────────────────────
class _ServiceFields(BaseModel):
    serviceName:            str                = Field(max_length=NAME_MAX)
    serviceCategory:        str                = Field(max_length=CATEGORY_MAX)
    department:             str                = Field(max_length=DEPT_MAX)
    description:            Optional[str]      = Field(default=None, max_length=DESC_MAX)

    standardPrice:          Decimal
    costPrice:              Optional[Decimal]  = None
    taxApplicable:          bool               = False
    tax:                    Optional[TaxEnum]  = None

    allowDiscount:          bool               = False
    requiresDoctorApproval: bool               = False
    availableForOp:         bool               = False
    availableForIp:         bool               = False
    availableForEmergency:  bool               = False

    status:                 StatusEnum         = StatusEnum.Active
    remarks:                Optional[str]      = Field(default=None, max_length=REMARKS_MAX)

    @field_validator("serviceName", "serviceCategory", "department")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("description", "remarks")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("standardPrice")
    @classmethod
    def standard_price_positive(cls, v: Decimal) -> Decimal:
        if v <= 0:
            raise ValueError("Standard Price must be greater than zero")
        if v > PRICE_MAX:
            raise ValueError(f"Standard Price cannot exceed {PRICE_MAX}")
        return v

    @field_validator("costPrice")
    @classmethod
    def cost_price_in_range(cls, v: Optional[Decimal]) -> Optional[Decimal]:
        if v is None:
            return None
        if v < 0:
            raise ValueError("Cost Price cannot be negative")
        if v > PRICE_MAX:
            raise ValueError(f"Cost Price cannot exceed {PRICE_MAX}")
        return v

    @model_validator(mode="after")
    def business_rules(self):
        # Tax must be selected when Tax is applicable; cleared otherwise.
        if self.taxApplicable and self.tax is None:
            raise ValueError("Tax selection is required when Tax is applicable")
        if not self.taxApplicable:
            self.tax = None

        # Cost price cannot exceed the standard (selling) price.
        if self.costPrice is not None and self.costPrice > self.standardPrice:
            raise ValueError("Cost Price cannot exceed Standard Price")

        return self


# ── Request: Create (code auto-generated by SP) ──────────────
class ServiceCreate(_ServiceFields):
    createdBy: Optional[str] = None


# ── Request: Update (ServiceCode is immutable) ───────────────
class ServiceUpdate(_ServiceFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class ServiceResponse(BaseModel):
    id:                     int
    serviceCode:            str
    serviceName:            str
    serviceCategory:        str
    department:             str
    description:            Optional[str]
    standardPrice:          str
    costPrice:              Optional[str]
    taxApplicable:          bool
    tax:                    Optional[str]
    allowDiscount:          bool
    requiresDoctorApproval: bool
    availableForOp:         bool
    availableForIp:         bool
    availableForEmergency:  bool
    status:                 str
    remarks:                Optional[str]
    createdBy:              Optional[str]
    createdDate:            Optional[datetime]
    updatedBy:              Optional[str]
    updatedDate:            Optional[datetime]

    class Config:
        from_attributes = True
