from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StoreTypeEnum(str, Enum):
    Main     = "Main Store"
    Sub      = "Sub Store"
    Pharmacy = "Pharmacy Store"
    OT       = "OT Store"
    Lab      = "Lab Store"


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150
LOCATION_MAX = 255
INCHARGE_MAX = 100
CONTACT_MAX  = 20


# ── Shared field rules ───────────────────────────────────────
class _StoreFields(BaseModel):
    storeName:     str            = Field(max_length=NAME_MAX)
    storeType:     StoreTypeEnum
    location:      Optional[str]  = Field(default=None, max_length=LOCATION_MAX)
    inCharge:      Optional[str]  = Field(default=None, max_length=INCHARGE_MAX)
    contactNumber: Optional[str]  = Field(default=None, max_length=CONTACT_MAX)
    status:        StatusEnum     = StatusEnum.Active

    @field_validator("storeName")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Store Name is required and cannot be blank")
        return v.strip()

    @field_validator("location", "inCharge", "contactNumber")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None


# ── Request: Create (code auto-generated by SP) ──────────────
class StoreCreate(_StoreFields):
    createdBy: Optional[str] = None


# ── Request: Update (StoreCode is immutable) ─────────────────
class StoreUpdate(_StoreFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class StoreResponse(BaseModel):
    id:            int
    storeCode:     str
    storeName:     str
    storeType:     str
    location:      Optional[str]
    inCharge:      Optional[str]
    contactNumber: Optional[str]
    status:        str
    createdBy:     Optional[str]
    createdDate:   Optional[datetime]
    updatedBy:     Optional[str]
    updatedDate:   Optional[datetime]

    class Config:
        from_attributes = True
