import re
from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import datetime
from enum import Enum


class StatusEnum(str, Enum):
    Active   = "Active"
    Inactive = "Inactive"


# ── Field limits (kept in sync with the frontend LIMITS + DB columns) ──
NAME_MAX     = 150
CONTACT_MAX  = 100
MOBILE_MAX   = 20
EMAIL_MAX    = 150
GST_MAX      = 20
PAN_MAX      = 15
DRUG_MAX     = 50
ADDR_MAX     = 255
LOC_MAX      = 100
PIN_MAX      = 20
TERMS_MAX    = 50
CREDIT_MAX   = 365

_EMAIL_RE  = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")
_MOBILE_RE = re.compile(r"^\d{10,15}$")
_PAN_RE    = re.compile(r"^[A-Z]{5}[0-9]{4}[A-Z]$")
_GST_RE    = re.compile(r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]Z[0-9A-Z]$")


# ── Shared field rules ───────────────────────────────────────
class _VendorFields(BaseModel):
    vendorName:        str            = Field(max_length=NAME_MAX)
    contactPerson:     str            = Field(max_length=CONTACT_MAX)
    mobileNumber:      str            = Field(max_length=MOBILE_MAX)
    email:             str            = Field(max_length=EMAIL_MAX)

    gstNumber:         Optional[str]  = Field(default=None, max_length=GST_MAX)
    panNumber:         Optional[str]  = Field(default=None, max_length=PAN_MAX)
    drugLicenseNumber: Optional[str]  = Field(default=None, max_length=DRUG_MAX)

    address:           str            = Field(max_length=ADDR_MAX)
    city:              str            = Field(max_length=LOC_MAX)
    state:             str            = Field(max_length=LOC_MAX)
    country:           str            = Field(max_length=LOC_MAX)
    pinCode:           str            = Field(max_length=PIN_MAX)

    paymentTerms:      Optional[str]  = Field(default=None, max_length=TERMS_MAX)
    creditDays:        Optional[int]  = None

    status:            StatusEnum     = StatusEnum.Active

    @field_validator("vendorName", "contactPerson", "address", "city", "state", "country", "pinCode")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("This field is required and cannot be blank")
        return v.strip()

    @field_validator("drugLicenseNumber", "paymentTerms")
    @classmethod
    def blank_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip()
        return v or None

    @field_validator("mobileNumber")
    @classmethod
    def valid_mobile(cls, v: str) -> str:
        digits = re.sub(r"[\s+\-]", "", v)
        if not _MOBILE_RE.match(digits):
            raise ValueError("Mobile Number must be 10-15 digits")
        return v.strip()

    @field_validator("email")
    @classmethod
    def valid_email(cls, v: str) -> str:
        v = v.strip()
        if not _EMAIL_RE.match(v):
            raise ValueError("A valid Email is required")
        return v

    @field_validator("panNumber")
    @classmethod
    def valid_pan(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip().upper()
        if not v:
            return None
        if not _PAN_RE.match(v):
            raise ValueError("PAN must be in format AAAAA9999A")
        return v

    @field_validator("gstNumber")
    @classmethod
    def valid_gst(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.strip().upper()
        if not v:
            return None
        if not _GST_RE.match(v):
            raise ValueError("GST must be a valid 15-character GSTIN")
        return v

    @field_validator("creditDays")
    @classmethod
    def credit_in_range(cls, v: Optional[int]) -> Optional[int]:
        if v is None:
            return None
        if v < 0:
            raise ValueError("Credit Days cannot be negative")
        if v > CREDIT_MAX:
            raise ValueError(f"Credit Days cannot exceed {CREDIT_MAX}")
        return v


# ── Request: Create (code auto-generated by SP) ──────────────
class VendorCreate(_VendorFields):
    createdBy: Optional[str] = None


# ── Request: Update (VendorCode is immutable) ────────────────
class VendorUpdate(_VendorFields):
    updatedBy: Optional[str] = None


# ── Response ─────────────────────────────────────────────────
class VendorResponse(BaseModel):
    id:                int
    vendorCode:        str
    vendorName:        str
    contactPerson:     str
    mobileNumber:      str
    email:             str
    gstNumber:         Optional[str]
    panNumber:         Optional[str]
    drugLicenseNumber: Optional[str]
    address:           str
    city:              str
    state:             str
    country:           str
    pinCode:           str
    paymentTerms:      Optional[str]
    creditDays:        Optional[int]
    status:            str
    createdBy:         Optional[str]
    createdDate:       Optional[datetime]
    updatedBy:         Optional[str]
    updatedDate:       Optional[datetime]

    class Config:
        from_attributes = True
